### ISSUE TITLE
./configure ignores --src

### ISSUE THREAD

**Issue by voldyman** [Orc/discount#115]
the ./confgiure.sh file ignores the --src argument and tries to include configure.inc from the current dir, this causes problems when the current dir is not the project dir.

**Comment by Orc** [comment]
Sadly, it's not just `configure.sh` that's the problem here; the rest of the build would fail even if I picked out the dirname and used it to find `configure.inc` :-(    For now, I'm going to have to mark this as an insurmountable opportunity and close it.
