### ISSUE TITLE
--relaxed-emphasis not available

### ISSUE THREAD

**Issue by emersion** [Orc/discount#117]
In the doc, we can find the `--relaxed-emphasis` option for `./configure`, but it has disappeared from the source code. How to enable this?

**Comment by Orc** [comment]
It's obsolete;  relaxed emphasis is now a runtime flag (MKD_NORELAX to disable it; -frelax, -f!relax, -fnorelax to the markdown program.)   The documentation, including online, is a bit out of date and is in the throes of being updated.
