### ISSUE TITLE
Failing test schiraldi.t in Discount 2.1.8 on Solaris 10

### ISSUE THREAD

**Issue by dago** [Orc/discount#121]
I am building Discount 2.1.8 on Solaris 10 Sparc with Sun Studio compiler
and get one failing test:
```
footnotes inside reparse sections .................... OK
Bugs & misfeatures reported by Mike Schiraldi ........
autolink café_racer
source:
        http://en.wikipedia.org/wiki/café_racer
diff:
        1c1
        < <p><a href="http://en.wikipedia.org/wiki/caf%C3%A9_racer">http://en.wikipedia.org/wiki/caf%C3%A9_racer</a></p>
        ---
        > <p><a href="http://en.wikipedia.org/wiki/caf">http://en.wikipedia.org/wiki/caf</a>é_racer</p>

tests/schiraldi.t: 19 tests; 1 failed/18 passed
```

**Comment by Orc** [comment]
Very late, but I tracked this down;  As best I can tell I fell victim to "all the world's a VAX" syndrome and didn't explicitly test for utf-8 characters when handling autolinks.   So the `%C3` prefix of `é` fell afoul of `isspace()` and was kicked out as a whitespace character.

Revision https://github.com/Orc/discount/commit/c60dab9d2404b5f3f54085e72e0159b4e1e2cab8 should  fix this defect?

**Comment by dago** [comment]
This test now passes, when applied to 2.1.8a I now get another failure:
```
(new) table-of-contents support ......................
toc item with link
source:
        ##[H2](H2) here
diff:
        4c4
        <   <li><a href="#H2.here">H2 here</a></li>
        ---
        >   <li><a href="#H2%20here">H2 here</a></li>
        8c8
        < <a name="H2.here"></a>
        ---
        > <a name="H2%20here"></a>

toc item with non-alpha start
source:
        #1 header
diff:
        2c2
        <  <li><a href="#L1.header">1 header</a></li>
        ---
        >  <li><a href="#1%20header">1 header</a></li>
        4c4
        < <a name="L1.header"></a>
        ---
        > <a name="1%20header"></a>

tests/toc.t: 3 tests; 2 failed/1 passed
```

**Comment by Orc** [comment]
That's an odd one;  can you show me your config.log and the output from `make clean;make` ?

**Comment by dago** [comment]
Sure, see the files attached. Please note that I am using a slightly different build environment:
  https://buildfarm.opencsw.org/source/xref/opencsw/csw/mgar/pkg/discount/trunk/Makefile

Strangely I cannot attach files here ("Attaching documents requires write permission to this repository.  Try again with a PNG, GIF, or JPG."), please find the files here:
  https://buildfarm.opencsw.org/~dam/discount/

I also have two private patches which I didn't open issues for yet:
1. Solaris needs an include to [alloca.h](https://buildfarm.opencsw.org/source/xref/opencsw/csw/mgar/pkg/discount/trunk/files/0001-Add-specific-include-for-alloca.patch) for alloca()
2. The build needs [LDFLAGS](https://buildfarm.opencsw.org/source/xref/opencsw/csw/mgar/pkg/discount/trunk/files/0002-We-don-t-have-ldconfig-and-the-line-forces-exitcode-.patch)

Best regards -- Dago

**Comment by Orc** [comment]
Okay, found it;  the toc test for idanchor wasn't explicitly turning url encoding on or off, but was assuming a build without url encoding on by default.   HEAD now has those tests tweaked; see if they work.

I'll add an alloca.h test into configure.sh  (which, btw, is not meant to be a clone of the horrific gnu configure, so contra your comment in the csw it's not crappy because it doesn't include the approximately 35 million different configurable directories gnu configure has!) -- does theme just refuse to build when alloca.h is not included, or does it spit out an annoying error message and continue?

**Comment by dago** [comment]
I just cloned from HEAD and all tests pass now. Thanks!

Without the inclusion of `alloca.h` the build bails out with
```
/opt/SUNWspro/bin/cc -I. -fPIC -xO3 -m32 -xarch=sparc -L. -m32 -xarch=sparc -L/opt/csw/lib -o theme theme.o pgm_options.o -lmarkdown 
Undefined                       first referenced
 symbol                             in file
alloca                              theme.o
ld: fatal: symbol referencing errors. No output written to theme
```

I didn't mean to offend you with the comment, it is just that I maintain roughly 1400 packages and dealing with a non-standard build system and looking at what options need to be passed regardless of the quality just draws from my scarce time I spent on packaging, so sometimes I can't hold myself of writing grumpy comments.

Best regards -- Dago

**Comment by Orc** [comment]
You didn't offend me with the comment, it's just that's it's not gnu configure (which is a pretty terrifying thing to build against) so of course it won't take the same arguments :-)

I'll make a configure.sh test for alloca; if it actually fails it's easy to test .

**Comment by Orc** [comment]
FYI, I put a check for alloca.h into configure.sh; it's at HEAD right now.

**Comment by dago** [comment]
Just verified, looks good. Thanks!
