### ISSUE TITLE
Convert compiletime syntax configuration settings to runtime flags

### ISSUE THREAD

**Issue by binki** [Orc/discount#124]
To make discount more usable as a shared tool and library, I think it would be better if all syntax variations could be configured at runtime. If the tool needs to be used to process different types of markdown on the same system, it should be possible to access all of the different syntax variations through the tool as long as it is compiled with support for that. For example, if I run `./configure.sh --with-fenced-code`, I should be able to opt out of fences with `markdown -f -fencedcode` rather than having to compile a different binary with `./configure.sh`.

For reference, this is my conclusion when considering [gentoo bug #554520](https://bugs.gentoo.org/show_bug.cgi?id=554520).

This would help a lot with the case where discount is installed system-wide and used by multiple different applications or scripts for different purposes. I suspect that some applications might even want to be able to use different options or allow the user to enable/disable them at runtime, but there are quite a few options that remain compiletime.

It looks like there are 23 flags right now, so with the max at 31 there should be enough for all of the `./configure.sh` options (6: dldiscout, dlextra, idanchor, githubtags, fencedcode, urlencodedanchor leaves flag values 30 and 31 open). If you’d be willing to accept a patch with this change, I think I could manage to write one, just let me know. I would drop all of the the relevant flags from `./configure.sh` and expose them only as flags. Unfortunately, this would be a breaking change for anyone who has used `./configure.sh` to customize discount before, but I think trying to keep compatibility would be unnecessarily dirty.

**Comment by Orc** [comment]
I have absolutely no objection to pulling configure-time options out and making them into flags.  If you want to make a patch that runtimifies everything, I will happily accept it and merge it into the mainline code.

**Comment by Orc** [comment]
No need to leave this open because binki fixed the wagon for me!  Thanks!
