### ISSUE TITLE
LaTeX support?

### ISSUE THREAD

**Issue by rndbrtrnd** [Orc/discount#128]
Hi.

I have some trouble with LaTeX formula, don't know if LaTeX is officially supported.

Look at the following formula:

$$
M = \left\{ c \in  \mathbb{C} | \lim_{n\to\infty} Z_n \neq \infty \right\}
\begin{align}
& Z_0 = c \\
& Z_{n+1} = Z_n^2 + c
\end{align}
$$

I had to add a couple of \ to make it work properly. For example, the first two _ are replaced by the <em> tag without the . So anything between $$ should be kept as-is.

Would be great to have a LaTeX support if it is not currently supported. At least, to manage properly with  `\` would be very useful.

Ar.

Note, for reference: https://github.com/davidfstr/rdiscount/issues/130#issuecomment-135832693

**Comment by Orc** [comment]
Is there any sort of standard way of embedding latex inside other documents?

**Comment by leonsim** [comment]
Both inline mode and block mode LaTex are supported. See https://github.com/Orc/discount/pull/127

**Comment by Orc** [comment]
Whoops.  I never actually bothered to close this when I collapsed issue #127 into the baseline.

Right now a block of latex
~~~
$$
this is latex.  Or not.
$$
~~~

Is just treated as an inline block, and produces the output
~~~
<p>$$
this is latex. Or not.
$$</p>
~~~

Which, unless the extra paragraph blocking around it is a complete showstopper should fix your issue?
