### ISSUE TITLE
Multiple calls to `mkd_document` result in <NUL> chars

### ISSUE THREAD

**Issue by koenpunt** [Orc/discount#132]
You can reproduce the problem if you alter `makepage.c`.

1. Add `mkd_xhtmlpage(doc, flags, stdout);` on line 87
1. Build: `make makepage`. 
1. Transform a markdown file, for example the README.md:

        ./makepage < Plan9/README.md > makepage.log

1. check right before the final `</body>` tag
![image](https://cloud.githubusercontent.com/assets/351038/10718514/2d23bef0-7b75-11e5-9b42-055a5baa4f71.png)

**Comment by Orc** [comment]
Got it; I add a null past the end of the generated html (in `mkd_document()`) but for some bizarre reason I added that null EVERY TIME I called that function, no matter whether I had to generate the html or not.  A simple shuffle of that code into the !p->html block fixed that wagon.

**Comment by Orc** [comment]
Fix: https://github.com/Orc/discount/commit/e7e9f4313285b7a5673893bd1a9a790258f3a0f0
