### ISSUE TITLE
Small technicality when building inside directories with spaces in name

### ISSUE THREAD

**Issue by Jeffrey-P-McAteer** [Orc/discount#135]
configure.inc erroneously reports that a makefile does not exist if the build directory is under a directories with spaces in it's name, putting quotes around the $__d and ${makefile} variables fixes nicely. I would pull/push/whatever to fix myself, but git is still very new to me.

<img width="317" alt="screenshot 2015-10-28 10 42 23" src="https://cloud.githubusercontent.com/assets/15269507/10791839/96d141fa-7d60-11e5-8e44-a474d4dd0c05.png">
<img width="554" alt="screenshot 2015-10-28 10 41 53" src="https://cloud.githubusercontent.com/assets/15269507/10791830/861b795c-7d60-11e5-8467-8649d0a73b61.png">

**Comment by Orc** [comment]
Whoops!  Try updating your copy to revision https://github.com/Orc/discount/commit/a1e812efa1347d0352b2a4f41697b91217e92633 and try it again.  I tested with a source directory of `d iscount` and got a bunch of places where it complained, so I went through and promiscuously quoted every instance of $__d and $__cwd!

**Comment by Orc** [comment]
Possibly all fixed now, and I've made a release (2.2.2) with a bunch of configure tweaks to hopefully catch all the places where space-including directories can blow up.   So I'll close this and cross my fingers!
