### ISSUE TITLE
Should mkd_compile recompile when flags has changed?

### ISSUE THREAD

**Issue by koenpunt** [Orc/discount#136]
Currently, when `mkd_compile` is called twice with different flags, it will still result in the same output, because only the `compiled` property of the `Document` is checked.

**Comment by Orc** [comment]
As of right now it doesn't recompile if the flags are changed.   I _think_ it would be easy to modify mkd_compile to compare the existing context to the new flags and reprocess if they have changed,
but I'd have to spend some time tracing the code to see what needs to be discarded.   Some things
require a complete reread (fenced code blocks differently than nonfenced code, alpha lists will break into paragraphs + code blocks, ditto for definition lists, and `<style>` blocks would become bizarre html blocks instead) so it may involve too much mysterious behavior to let `mkd_compile()` recompile with some flags and not others.

**Comment by Orc** [comment]
I made up some experimental code that dumps the old compiled document and regenerates if the flags change.   I've cloned it over to github and it's at HEAD right now.   Test it and tell me what explodes when you do it.

**Comment by koenpunt** [comment]
Looks good, no problems thus far, thanks! 

Should the same be done for when the callbacks change?

**Comment by Orc** [comment]
Probably;  it's not quite as easy as checking the flags, so I'll have to think over what's the best way to do it.

**Comment by koenpunt** [comment]
I figure simply setting `doc->compiled` to `0` and freeing `code` and `ctx` when one of `mkd_e_url`, `mkd_e_flags`, `mkd_e_free`, `mkd_e_data` is called is not going to work?

**Comment by Orc** [comment]
I think that would work, but I'm considering either making a free-only-those-things function that all of the mkd_e_foo functions call, or adding a dirty flag to the mmiot to tell mkd_compile to flush and regenerate.

**Comment by Orc** [comment]
I'm going to ignore the rest of this issue for now (until the next version is released), but not close it.   When 2.2 is released can you run some sanity tests for me (or send me some sample code I can stuff into my test suite?)

**Comment by koenpunt** [comment]
I haven't been to active in integrating discount lately, but sure, just let me know when you want me to test it :)

**Comment by Orc** [comment]
Okay, it *might* be working the way you need now;  I've added a dirty flag that does the same as testing if the flags have changed (sets dirty if a callback actually changes, and then it does the same backend content dump as if the flags changed) and pushed here.
