### ISSUE TITLE
Is there a way to make `theme` include files from within a markdown document?

### ISSUE THREAD

**Issue by somasis** [Orc/discount#137]
I'm trying to include an HTML document from within a markdown document. Is there a way I can do this without having to make another template just for this one page?

**Comment by Orc** [comment]
Sorry I didn't get back to you about this earlier, but not easily;  theme passes the markdown off to the markdown library, which doesn't define an include syntax.   Maybe wrap the whole shebang in a shell or m4 wrapper that does the include, then feeds the offending document to theme?
