### ISSUE TITLE
AddressSanitizer: heap-buffer-overflow  - Invalid memory access 

### ISSUE THREAD

**Issue by fmunozs** [Orc/discount#138]
> root@kali:~/markdown/discount-2.1.8a# valgrind markdown min76.txt 
> ==18005== Memcheck, a memory error detector
> ...
> ==18005== Invalid read of size 1
> ==18005==    at 0x404A379: islist (in /usr/lib/i386-linux-gnu/libmarkdown.so.2.1.8)
> ==18005==    by 0x404AA38: compile (in /usr/lib/i386-linux-gnu/libmarkdown.so.2.1.8)
> ==18005==    by 0x404B82D: mkd_compile (in /usr/lib/i386-linux-gnu/libmarkdown.so.2.1.8)
> ==18005==    by 0x804920B: ??? (in /usr/bin/markdown)
> ==18005==    by 0x407470D: (below main) (in /lib/i386-linux-gnu/i686/cmov/libc-2.21.so)
> ==18005==  Address 0x4214369 is 0 bytes after a block of size 1 alloc'd
> ==18005==    at 0x402B1DC: malloc (vg_replace_malloc.c:299)
> ==18005==    by 0x404A040: splitline (in /usr/lib/i386-linux-gnu/libmarkdown.so.2.1.8)
> ==18005==    by 0x404C010: mkd_compile (in /usr/lib/i386-linux-gnu/libmarkdown.so.2.1.8)
> ==18005==    by 0x804920B: ??? (in /usr/bin/markdown)
> ==18005==    by 0x407470D: (below main) (in /lib/i386-linux-gnu/i686/cmov/libc-2.21.so)
> ==18005== 
> 

ASAN enabled build

> root@kali:~/markdown/discount-2.1.8a# ./markdown min76.txt 
> =================================================================
> ==17904==ERROR: AddressSanitizer: heap-buffer-overflow on address 0xb57007d1 at pc 0x0805c98e bp 0xbffff068 sp 0xbffff05c
> READ of size 1 at 0xb57007d1 thread T0
>     #0 0x805c98d in islist /root/markdown/discount-2.1.8a/markdown.c:516
>     #1 0x8065af7 in compile /root/markdown/discount-2.1.8a/markdown.c:1267
>     #2 0x8068d18 in compile_document /root/markdown/discount-2.1.8a/markdown.c:1169
>     #3 0x8068d18 in mkd_compile /root/markdown/discount-2.1.8a/markdown.c:1339
>     #4 0x804a742 in main /root/markdown/discount-2.1.8a/main.c:201
>     #5 0xb78cd70d in __libc_start_main (/lib/i386-linux-gnu/i686/cmov/libc.so.6+0x1870d)
>     #6 0x804b87b  (/root/markdown/discount-2.1.8a/markdown+0x804b87b)
> 
> 0xb57007d1 is located 0 bytes to the right of 1-byte region [0xb57007d0,0xb57007d1)
> allocated by thread T0 here:
>     #0 0xb7afe25e in __interceptor_malloc (/usr/lib/i386-linux-gnu/libasan.so.2+0x9225e)
>     #1 0x8070710 in splitline /root/markdown/discount-2.1.8a/markdown.c:174
>     #2 0x8070710 in htmlblock /root/markdown/discount-2.1.8a/markdown.c:326
>     #3 0x8070710 in compile_document /root/markdown/discount-2.1.8a/markdown.c:1141
>     #4 0x8070710 in mkd_compile /root/markdown/discount-2.1.8a/markdown.c:1339
> 
> SUMMARY: AddressSanitizer: heap-buffer-overflow /root/markdown/discount-2.1.8a/markdown.c:516 islist
> Shadow bytes around the buggy address:
>   0x36ae00a0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
>   0x36ae00b0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
>   0x36ae00c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
>   0x36ae00d0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
>   0x36ae00e0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
> =>0x36ae00f0: fa fa fa fa fa fa fa fa fa fa[01]fa fa fa 00 00
>   0x36ae0100: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
>   0x36ae0110: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
>   0x36ae0120: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
>   0x36ae0130: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
>   0x36ae0140: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
> Shadow byte legend (one shadow byte represents 8 application bytes):
>   Addressable:           00
>   Partially addressable: 01 02 03 04 05 06 07 
>   Heap left redzone:       fa
>   Heap right redzone:      fb
>   Freed heap region:       fd
>   Stack left redzone:      f1
>   Stack mid redzone:       f2
>   Stack right redzone:     f3
>   Stack partial redzone:   f4
>   Stack after return:      f5
>   Stack use after scope:   f8
>   Global redzone:          f9
>   Global init order:       f6
>   Poisoned by user:        f7
>   Container overflow:      fc
>   Array cookie:            ac
>   Intra object redzone:    bb
>   ASan internal:           fe
> ==17904==ABORTING

Test case attached. Found using AFL.
[min76.txt](https://github.com/Orc/discount/files/114805/min76.txt)

**Comment by Orc** [comment]
Can you make your bug report a bit more succinct?   I don't actually see any reproducable defect here?

**Comment by fmunozs** [comment]
Sorry, please just try to parse the attached file under valgrind [1] and you will see reports about invalid reads:
 Invalid read of size 1
 at 0x404A379: islist (in /usr/lib/i386-linux-gnu/libmarkdown.so.2.1.8)

The ASAN [1] enabled build includes this memory error detection and it also shows this behaviour and it classifies the issue as "heap-buffer-overflow"

[1] http://valgrind.org/
[2] https://www.chromium.org/developers/testing/addresssanitizer

**Comment by Orc** [comment]
Actually, I'm more interested in input that doesn't render properly -- in most every case where there's been memory corruption it tracks back to an edge case that's rendering improperly.    Dumping valgrind output is not particularly useful here, because it's a /lot/ harder to backtrack than it is to trace .

**Comment by fmunozs** [comment]
I have several other test cases that give out invalid memory access but I'd like to identify if its the same issue as this one, I saw a commit for the test case but I'm not sure if you already fixed it. I'm gonna minimize them and test with the trunk version.

**Comment by Orc** [comment]
I would like to see the markdown source of these cases, please!   If you can find a case where markdown renders correctly (tested against the markdown dingus at daringfireball) but still makes your paranoia testers wig out, I'd be veeeery interested in seeing it.

**Comment by fmunozs** [comment]
I have around 70 different files that generate 6 different stack traces, since I don't want to send you a lot of duplicate files/reports, I will just report 5 additional bugs with one sample per bug, is it ok?

$ find  . -exec ./../../../markdown {} 2>&1 \; | grep "#0" | sort -u
#0 0x805a148 in quoteblock /root/markdown/discount-2.1.8a/markdown.c:797
#0 0x805c98d in islist /root/markdown/discount-2.1.8a/markdown.c:516
#0 0x8070da7 in isfootnote /root/markdown/discount-2.1.8a/markdown.c:347
#0 0x8071dbd in isfootnote /root/markdown/discount-2.1.8a/markdown.c:354
#0 0xb7af16f5 in __asan_memmove (/usr/lib/i386-linux-gnu/libasan.so.2+0x866f5)
#0 0xb7afd25e in __interceptor_malloc (/usr/lib/i386-linux-gnu/libasan.so.2+0x9225e) (this bugreport!)

**Comment by Orc** [comment]
Please don't; I'd like to see the offending markdown source first.

**Comment by fmunozs** [comment]
Attached minimized test cases, some may be duplicate bugs as I mentioned.

[min.zip](https://github.com/Orc/discount/files/128235/min.zip)

**Comment by Orc** [comment]
Thank you, this is very useful.  These test cases make your memory sanitizer suite scream about memory overruns with $HEAD or just with older versions of the code?

**Comment by fmunozs** [comment]
I used the current stable version only discount-2.1.8a.

**Comment by Orc** [comment]
It's possible that $HEAD corrects those defects, because it looks a lot like they're all variants on the `<p></>*` defect you originally reported.    I'm walking through them comparing discount's rendering to the reference rendering and it looks like $HEAD is now producing the correct output.

Alas, Valgrind doesn't build on my el capitan machine, so I can't easily check its output myself.

**Comment by Orc** [comment]
I tweaked the amalloc paranoia library to put a marker at the end of each allocated block and to dump core if it can't find the marker at realloc or free, added all of your sample source as test cases, and (except for a stupid braino where I didn't relocate the marker when realloc()ing) can't provoke memory overrun crashes on any of your test cases.   So I'm going to have to assume that either (a) the tweak I did to properly detect the end of html blocks fixed the problem or (b) valgrind is doing false positives;  in either case I think I've fixed the problem and am doing to close the bug report now.
