### ISSUE TITLE
ordered and unordered lists incorrectly merged

### ISSUE THREAD

**Issue by sumyungguy** [Orc/discount#139]
I came across this problem while trying to format some of my recipes using Discount in the "Notebooks" application from www.notebooksapp.com.

As an example, this markdown source:
```
Pancakes

- 1/2 cup flour
- 1/2 cup milk
- 1 egg
- pinch of salt

1. Mix ingredients together.
2. Pour into greased pan.
3. ???
4. Profit.
```
Produces this output:
```
<p>Pancakes</p>

<ul>
<li>1/2 cup flour</li>
<li>1/2 cup milk</li>
<li>1 egg</li>
<li><p>pinch of salt</p></li>
<li><p>Mix ingredients together.</p></li>
<li>Pour into greased pan.</li>
<li>???</li>
<li>Profit.</li>
</ul>
```

Which renders more or less like this:
```
Pancakes

    * 1/2 cup flour
    * 1/2 cup milk
    * 1 egg
    * pinch of salt 

    * Mix ingredients together. 

    * Pour into greased pan.
    * ???
    * Profit. 
```

That can't be right.

I checked some other implementations, and found that pandoc, commonmark, PHP markdown, kramdown, and several others, did what I expected, i.e.:

```
Pancakes

    * 1/2 cup flour
    * 1/2 cup milk
    * 1 egg
    * pinch of salt

    1. Mix ingredients together.
    2. Pour into greased pan.
    3. ???
    4. Profit.
```
Some others did what Discount does, while still others, including Gruber's dingus, also converted the ordered list to unordered, but with different variations of the line spacing. I think it's clearly a bug in those implementations. Gruber's description of the syntax - and common sense - would say that an unindented `1.` following a blank line, should close the preceding unordered list, and start a new ordered one. There should never be a case where a `1.` is rendered as a bullet.

Github gets it almost right, but not quite:

Pancakes

- 1/2 cup flour
- 1/2 cup milk
- 1 egg
- pinch of salt

1. Mix ingredients together.
2. Pour into greased pan.
3. ???
4. Profit.

**Comment by Orc** [comment]
Alas, this is not a bug.  I try to follow the behavior of the reference implementation as closely as possible, and it does the exact same behavior :-(

See:
~~~~~
<p>Pancakes</p>

<ul>
<li>1/2 cup flour</li>
<li>1/2 cup milk</li>
<li>1 egg</li>
<li><p>pinch of salt</p></li>
<li><p>Mix ingredients together.</p></li>
<li>Pour into greased pan.</li>
<li>???</li>
<li>Profit.</li>
</ul>
~~~~~

**Comment by sumyungguy** [comment]
I can understand that. After googling a bit more, I can see it's been discussed in many places.

Still, it would be nice if you could maybe offer it as an option, as was done on another "markdown.pl purist" project :-) 
https://github.com/waylan/Python-Markdown/issues/64

This particular behavior of markdown.pl - which hasn't been updated since 2004 - is especially nonsensical, and contradict's Gruber's own description of the syntax:
> Unordered lists use asterisks, pluses, and hyphens — interchangably — as list markers

It's clear he never intended `1.` to also serve as an unordered list marker, or to make writing my simple pancake recipe completely impossible to do in markdown. If he did, it's very difficult to understand why. Especially in something like the Notebooks mac app, it's unexpected and buggy. It seems like this is a case where strictly sticking to the original markdown.pl behavior doesn't benefit your users.

Thanks...

**Comment by Orc** [comment]
Alas, the reference implementation still merges lists of various types, so I'm stuck with this bit of correct, if somewhat maddening, behavior :-(

**Comment by jesperronn** [comment]
same as #150

**Comment by Orc** [comment]
Took the last of my available flag bits and added the flag `MKD_EXPLICITLIST`, which splits lists on ordered vs. unordered list boundaries.   This screamingly breaks standard compliance, so it's only an option, and is likely to drag me over the edge of having to completely break the interface to fit more markdown extension flags in sometime in the nearer than I want future.
