### ISSUE TITLE
GFM fenced code blocks: No longer accepts blank lines?

### ISSUE THREAD

**Issue by davidfstr** [Orc/discount#143]
It appears that including a blank line in the middle of a GFM fenced code block now causes the fenced code block to not be recognized. Details below.

This appears to be a regression from Discount 2.1.8 behavior. It causes the RDiscount test suite (which exercises Discount) to break.

### Configuration

```
git clone https://github.com/Orc/discount.git
cd discount/
git checkout v2.2.0
./configure.sh --enable-all-features
make
```

### Repro Steps, Actual Results, Expected Results

https://gist.github.com/davidfstr/29f6552bf439b32e2d72a4784b5e0060

### Notes

For Discount 2.1.8, a different configure.sh line was used. Specifically:

* Discount 2.1.8
     * `./configure.sh --with-fenced-code --with-github-tags --with-dl=both`
* Discount 2.2.0
    * `./configure.sh --enable-all-features`

Not sure if some other feature enabled by `--enable-all-features` is interfering with GFM fenced code blocks.

**Comment by Orc** [comment]
Hmm.  Fenced code is now a runtime option, defaulting to disabled.   Perhaps that's it?   When I run the commandline tool in 2.2.0 __without__ the flag **MKD_FENCEDCODE** fencing doesn't work, but **markdown&nbsp;-ffencedcode** does.

**Comment by davidfstr** [comment]
+1 to make MKD_FENCEDCODE (and other options) runtime options rather than configure-time options. Using MKD_FENCEDCODE fixes the issue.

I'm surprised that GFM FCBs were sometimes kinda-sorta working even without MKD_FENCEDCODE.

**Comment by Orc** [comment]
Fenced blocks with backtick or tilde?   If backtick, it was just a big old inline \<code\> block.
