### ISSUE TITLE
Definition lists no longer work in Discount 2.2.0?

### ISSUE THREAD

**Issue by davidfstr** [Orc/discount#144]
Discount 2.1.8 could be configured to process definition lists with:

```
./configure.sh --with-fenced-code --with-github-tags --with-dl=both
```

In Discount 2.2.0 I used the following configure line to hopefully achieve the same effect:

```
./configure.sh --enable-all-features
```

However the following definition list does not appear to be processing the same way as in 2.1.8:
https://gist.github.com/davidfstr/17742d3e88d3dd7c2835810888d3209c

**Comment by Orc** [comment]
It's a side-effect of a patch from @binki -- he gave me a handful of patches that converted most of the compile-time flags to runtime flags, and I didn't think to tweak **--enable-all-features** to flip those flags on by default.

**Comment by davidfstr** [comment]
Confirmed that adding the new MKD_DLEXTRA flag restores support.
