### ISSUE TITLE
Behavior of --enable-all-features is not documented

### ISSUE THREAD

**Issue by davidfstr** [Orc/discount#145]
There is a new configure option `--enable-all-features` which replaces a lot of older options. Unfortunately I can find no documentation anywhere that explains what it does. What constitutes "all features"?

(1) Here's what `./configure.sh --help` says:

```
--enable-all-features	Turn on all stable optional features
```

(2) The [main project page] contains no mention of `--enable-all-features` at all.

[main project page]: http://www.pell.portland.or.us/~orc/Code/discount/

There should be an explanation documented somewhere.

**Comment by Orc** [comment]
Yes, you are quite correct.  There aren't many features left for **--enable-all-features** anymore (just amalloc) but it's never actually been documented.   I'll fix that for 2.2.1 :-(
