### ISSUE TITLE
Rename muñoz.t for compatibility with OS X/Sourcetree

### ISSUE THREAD

**Issue by Coeur** [Orc/discount#146]
Hi,

Could you change the encoding of filename muñoz.t for compatibility with OS X/Sourcetree? Thanks.

**Comment by Orc** [comment]
By OS X you mean macosx, or something else?   I am completely unfamiliar with sourcetree; what is it?

**Comment by Coeur** [comment]
Yes, [Mac OS X got renamed four years ago](http://www.theverge.com/2012/2/16/2802281/apple-officially-renames-mac-os-x-to-os-x-drops-the-mac), and will be rebranded yet again on 17th June 2016, but that's a different story. [SourceTree](https://www.sourcetreeapp.com/) is a popular git IDE from Atlassian.

I think the file system is [HFS+](https://en.wikipedia.org/wiki/HFS_Plus). When cloning on it, the file muñoz.t seems not found in the git index. Renaming to "munoz.t" would solve the issue.

**Comment by Orc** [comment]
I think that may be a defect in SourceTree;  git & macosx natively supports utf-8 filenames (as does Linux and FreeBSD.)   You should ask Atlassian if it's a known defect in their product.

**Comment by Coeur** [comment]
I've already asked. But it would be nice to apply a workaround for now, don't you think?

**Comment by Orc** [comment]
You are quite welcome to rename that file in your personal repository, but given that macos, git, linux, and freebsd are capable of handling utf-8 filenames I'm not really willing to rename it on the baseline SCCS tree to compensate for one broken third-party IDE.
