### ISSUE TITLE
Improper handling of consecutive bullet lists

### ISSUE THREAD

**Issue by davidfstr** [Orc/discount#150]
### Input

```
$ ./markdown -V
markdown: discount 2.2.0
$ ./markdown
- hi
- there

1. first
2. second
^C
```

### Expected Output

```
<ul>
<li>Bullet</li>
<li>Bullet</li>
</ul>
<ol>
<li>Numbered</li>
<li>Numbered</li>
</ol>
```

### Actual Output

```
<ul>
<li>hi</li>
<li><p>there</p></li>
<li><p>first</p></li>
<li>second</li>
</ul>
```

### Notes

If anything is inserted between the lists (like ----), the result is fine.

Original issue reported downstream at: https://github.com/davidfstr/rdiscount/issues/137

**Comment by Orc** [comment]
Sadly, this is not a defect; it's the way markdown processes lists :-(

I'm working on yet another effing option flag to process lists in the expected nonsurprising manner, but it has to be an option because the reference implementation merges adjacent lists no matter what type they are.

**Comment by Orc** [comment]
See my comment to version #139
