### ISSUE TITLE
How to use this library on VS 2015 (Windows 10 x64)?

### ISSUE THREAD

**Issue by LegendRhine** [Orc/discount#154]
How to compile and use it in VS 2015?

Thanks

**Comment by LegendRhine** [comment]
Or anyone could share this static-library (both on windows x64 and macOS) and a Mkdio.h?

**Comment by Orc** [comment]
I don't have any windows machines (and work pretty much universally on a Unix command line) so I don't know if I can help much.   If you can load a Cygwin environment onto your machine, running configure.sh in it will give you most of what you need for a native windows machine, and you'll only need to go in and hand edit config.h (to define DWORD, WORD, BYTE; the library doesn't care about the PATH_{whatever} defines) and mkdio.h (to define DWORD for mkd_flag_t)

If you get it working, I'd love to get copies of your mkdio.h and config.h;  I could set up a VS directory with the files needed to build discount under it.

**Comment by tin-pot** [comment]
@LegendRhine Maybe you might take a look at my fork of _discount_ for MSVC. It does however lag somewhat behind, mostly because the bitvector for options has run out of space (see the `MKD_*` macros in `markdown.h`), as I had added some own options in the meantime ...
https://github.com/tin-pot/discount

**Comment by Orc** [comment]
Take a look at @tin-pot & @mloskot's work with vc++ (the latter merged into the msvc subdirectory in my mainline) -- one of these might work for you?

**Comment by LegendRhine** [comment]
Thanks Orc. Finally, I wrote a Markdown parser by myself :) It's very rough and simple at the present...

**Comment by LegendRhine** [comment]
Also, many thanks for tin-pot :)

**Comment by Orc** [comment]
You wrote your own?  Yay, the more the merrier :-)
