### ISSUE TITLE
<form> element shouldn't be surrounded by <p> in the output

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [Orc/discount#156]
According to [Daring Fireball: Markdown Syntax Documentation](http://daringfireball.net/projects/markdown/syntax.php#html), HTML block-level elements can be used in Markdown as long as it is separated by blank lines, however in the Discount's generated output the `<form>` tags are surrounded by `<p>`

input:

```markdown
# test form element surrounded by p element

<form>

</form>
```

output:

```html
<h1>test form element surrounded by p element</h1>

<p><form></p>

<p></form></p>
```

I'm using Discount 2.1.8-2 from Ubuntu software archive.  (UPDATE: reproduced in current latest commit 8c670e0 as well)

Workaround: put the `<form>` in a `<div>` works

```html
<h1>test form element surrounded by p element</h1>

<div>
<form>

</form>
</div>
```

**Comment by Orc** [comment]
Whoops!  I didn't include <form> in my big list of html block elements (mktag.c);  Added (mktag.c; tests/html.t), committed, and pushed to sccs.
