### ISSUE TITLE
Add support for GitHub fenced code blocks

### ISSUE THREAD

**Issue by vigilancer** [Orc/discount#160]
GitHub allows specify code blocks with 'fences':
https://help.github.com/articles/creating-and-highlighting-code-blocks/

In a nutshell it adds another syntax to distinct codeblocks. What good about it comparing to [default](http://daringfireball.net/projects/markdown/syntax#precode), one should not change whole code and add indentation to it. 

Also it is possible to explicitly tell what language is in the block. 
It's quite convenient, even critical to have when using client-side syntax highlighters like [Highlight.js](http://highlightjs.org/) (see below).

<pre>
```
{code}
```
</pre>
generates:
<pre>
&lt;pre&gt;&lt;code&gt;{code}&lt;/code&gt;&lt;/pre&gt;
</pre>

and

<pre>
```java
{java-code}
```
</pre>
generates:
&lt;pre&gt;&lt;code class=&quot;java&quot;&gt;{java-code}&lt;/code&gt;&lt;/pre&gt;

**Comment by Orc** [comment]
Support for fenced code blocks is already in discount;  Use the MKD_FENCEDCODE flag if you're calling it from software, -ffencedcode if you're running the markdown, theme, or mkd2html programs.

(Alas, it's not adequately documented -- the only reference to it is in the markdown(3) manpage -- but it does work.)
