### ISSUE TITLE
Please allow empty definitions in definition lists

### ISSUE THREAD

**Issue by rrthomas** [Orc/discount#170]
At present it's not possible to have a definition list with no actual definition bodies, e.g.

    =foo=
    =bar=

A workaround is to write them as HTML, but that can mean a lot of work if one wants to add an empty definition to the bottom of an existing list!

**Comment by Orc** [comment]
The current logic for a definition list wants an indented object immediately after the =tag=, so it wouldn't be easy to change that without making the parser too greedy.    As a workaround, have you considered doing

~~~~
=tag=
    <!-- not defined -->
~~~~

Which gives an empty `<dd>` block?

**Comment by rrthomas** [comment]
I hadn't; thanks, that's a much less disruptive workaround. Perhaps you could add it to the docs?

**Comment by Orc** [comment]
(Finally documented, so closing it out)
