### ISSUE TITLE
pkgconfig/libmarkdown.pc is not installed

### ISSUE THREAD

**Issue by reagentoo** [Orc/discount#172]
After install lib/pkgconfig is empty.

**Comment by Orc** [comment]
Whoops.   I don't actually use the whole GNU .pc libtool environment, so when I dropped a dependency stanza into the middle of the install rule I didn't notice it.   I've taken it out, pushed the changes to the mirror here, and _hopefully_ your system will get a pkgconfig entry.

**Comment by reagentoo** [comment]
Everything ok now. Thank you.
