### ISSUE TITLE
LaTex is not working

### ISSUE THREAD

**Issue by AlexD97** [Orc/discount#173]
Hello,

Latex is not working for me. 
Something like 

```
$$
5x_1
$$
```

will be processed to `$$5x_1$$` despite having the `MKD_LATEX` flag set in `mkd_in()` and `markdown()`.

**Comment by Orc** [comment]
Which version of discount are you using, and what is your expected output?

**Comment by AlexD97** [comment]
I use version 2.2.2

I would expect 5x₁ as my output.

**Comment by Orc** [comment]
Ah.  I think that this is a failure in the documentation, then;  discount doesn't do the latex processing itself, but just passes what's between the $$ .. $$ pair through unprocessed for a separate latex processor to handle.

**Comment by AlexD97** [comment]
Which latex processor would you recommend?

**Comment by Orc** [comment]
I don't use LaTeX myself, but Mathjax is the one that I did the LaTeX passthrough support for   (javascript, so maybe browser-only?)

**Comment by AlexD97** [comment]
Okay, thank you. It works fine with Mathjax.
