### ISSUE TITLE
Set multiple flags

### ISSUE THREAD

**Issue by AlexD97** [Orc/discount#174]
Is it possible to set multiple flags which are not interfering (e.g. MKD_LATEX and MKD_EXTRA_FOOTNOTE)?

**Comment by Orc** [comment]
From the command line program, -flatex -ffootnote (or -flatex,footnote);  from the library , MKD_LATEX|MKD_EXTRA_FOOTNOTE

**Comment by AlexD97** [comment]
Thank you.
