### ISSUE TITLE
Use best practices when creating CMake project files

### ISSUE THREAD

**Issue by imikejackson** [Orc/discount#181]
The CMakeLists.txt file should be at the top level and other refactoring. The current CMake files look pretty good as is. Probably just some minor changes.

 I would like to use this project in our own project (GitHub.com/bluequartzsoftware/dream3d) which is cross platform. I would like to ramp up the CMake support. This would get tested on a nightly basis on a variety of machines including VS2015, VS2017, Linux (Ubuntu 14.04 & 16.06) and macOS 10.10/11/12/13. Those results are posted to http://my.cdash.org/index.php?project=DREAM3D

**Comment by imikejackson** [comment]
Should bump the minimum version of CMake up to at least 3.6 to get some of the newer features and "modern" make coding practices.

**Comment by Orc** [comment]
I don't use cmake, so the current configuration minimizes the visual bloat at the toplevel directory.   If you'd like to tweak the cmake configuration files, I'll happily accept patches as long as they don't move the cmake stuff to the top level directory.
