### ISSUE TITLE
Accepting all merge requests @ http://github.com/bluequartzsoftware/discount

### ISSUE THREAD

**Issue by imikejackson** [Orc/discount#182]
I am forking the repo since you are unwilling to accept perfectly sound and impactful pull requests.

@podsvirov 
@mloskot

**Comment by Orc** [comment]
What?  You didn't open a pull request; you opened an issue and I invited patches?

**Comment by imikejackson** [comment]
I read your comments on the 2 current pull requests and you rejected them for unreasonable reasons.
