### ISSUE TITLE
Commonmark conformance

### ISSUE THREAD

**Issue by Crissov** [Orc/discount#184]
In the Discount homepage, you document how it passes Gruber’s test suites and what had to be hacked to achieve this. Could you please also document how your parser either conforms to or differs from [Commonmark](https://github.com/commonmark/CommonMark)?

**Comment by Orc** [comment]
I'm sorry, I don't know the first thing about commonmark except that it's a markdown variant that was developed well after discount was written :-(

**Comment by Crissov** [comment]
I'm also sorry that I don't know much about Discount other than it's used in RDiscount. Anyway, CM contains tools to run parsers against the [test suite](https://github.com/commonmark/CommonMark#running-tests-against-the-spec).

**Comment by Orc** [comment]
My primary compatibility concern is to stay as compatible as possible with John Gruber's Markdown implementation, so I'm sure discount isn't compatible with commonmark.

**Comment by Crissov** [comment]
Except for [clarifications and minor extensions](https://github.com/commonmark/CommonMark#differences-from-original-markdown), that is also the stated goal of the Commonmark project. I'm not asking you to change Discount to conform to Commonmark, but acknowledging the differences would be nice, because CM (being now the base of GFM) is more and more seen as the defacto standard variant of Markdown (whose original implementation and documentation did not always agree with each other).

**Comment by Orc** [comment]
"clarifications and minor extensions" leaves a _lot_ of wiggle room :-)

**Comment by Crissov** [comment]
That's why it's documented and there's a test suite.

**Comment by Orc** [comment]
Same for John Gruber's Markdown :-)

**Comment by Crissov** [comment]
… except where it’s internally inconsistent or underspecified

**Comment by Orc** [comment]
Markdown is documented and there are (two; one for John Gruber's first release, one for this later releases -- this is why I've got a MKD_1_COMPAT flag) test suites for it.      Yes, there are inconsistencies, but documentation and a test suite do exist, and this is why I publish my compliance with them.

But if I publish compatibility ratings against commonmark people may think I'm trying to be a commonmark implementation, and Discount is not a commonmark implementation.
