### ISSUE TITLE
linking on plan9 produces "incompatible type signatures" errors

### ISSUE THREAD

**Issue by mischief** [Orc/discount#193]
in plan 9, the compiler internally annotates functions with a hash representing the types used. this is sort of like C++'s name mangling.

because discount uses some type punning in various places (https://github.com/Orc/discount/blob/master/mkdio.h.in#L6), along with some inconsistently declared function declarations (https://github.com/Orc/discount/blob/06ac2cc08f9bf449fc464fbf412c5da1c0c8b2b7/mkdio.h.in#L34 https://github.com/Orc/discount/blob/06ac2cc08f9bf449fc464fbf412c5da1c0c8b2b7/mkdio.c#L203) the linker doesn't think these types match, and complains.

there are two solutions here.

we can turn off type signature checking entirely in the compiler, or we possibly can use a plan 9 compiler extension to disable type signatures for just the opaque types.

what do you think?

```
cc -D_BSD_EXTENSION -D_C99_SNPRINTF_EXTENSION -I. -FTVw -L. -o markdown main.o pgm_options.o gethopt.o notspecial.o -lmarkdown 
cc: flag -F ignored
cc: flag -V ignored
gfm_populate: incompatible type signatures f616e90f(main.o) and 209d3530(./libmarkdown.a(gfm_string)) for gfm_string
gfm_string: incompatible type signatures 4e8956c3(main.o) and b41706a6(./libmarkdown.a(gfm_string)) for gfm_in
mkd_css: incompatible type signatures 45c62911(main.o) and 226ab5ba(./libmarkdown.a(mkd_generatecss)) for mkd_generatecss
mkd_toc: incompatible type signatures 45c62911(main.o) and 226ab5ba(./libmarkdown.a(mkd_generatetoc)) for mkd_generatetoc
___mkd_freeLineRange: incompatible type signatures 6a8b6630(main.o) and fe8ae929(./libmarkdown.a(mkd_cleanup)) for mkd_cleanup
dumptree: incompatible type signatures c1beb9b0(main.o) and 75782cb9(./libmarkdown.a(mkd_dump)) for mkd_dump
mkd_dump: incompatible type signatures a618c465(main.o) and 82bd510e(./libmarkdown.a(mkd_dump)) for mkd_compile
populate: incompatible type signatures 4e8956c3(main.o) and b41706a6(./libmarkdown.a(__mkd_io_strget)) for mkd_in
__mkd_io_strget: incompatible type signatures f616e90f(main.o) and 209d3530(./libmarkdown.a(__mkd_io_strget)) for mkd_string
mkd_string: incompatible type signatures 45c62911(main.o) and 226ab5ba(./libmarkdown.a(__mkd_io_strget)) for mkd_generatehtml
mkd_generateline: incompatible type signatures fb2bd201(./libmarkdown.a(mkd_basename)) and d7d05eaa(./libmarkdown.a(__mkd_io_strget)) for mkd_e_url
mkd_e_url: incompatible type signatures fb2bd201(main.o) and d7d05eaa(./libmarkdown.a(__mkd_io_strget)) for mkd_e_flags
mkd_e_flags: incompatible type signatures a7158ab9(./libmarkdown.a(mkd_basename)) and 83ba1762(./libmarkdown.a(__mkd_io_strget)) for mkd_e_free
mkd_e_free: incompatible type signatures 25e7559e(./libmarkdown.a(mkd_basename)) and 28be247(./libmarkdown.a(__mkd_io_strget)) for mkd_e_data
mkd_e_data: incompatible type signatures f69bdc2a(main.o) and d34068d3(./libmarkdown.a(__mkd_io_strget)) for mkd_ref_prefix
cc: 6l: 6l 2647029: error
*** Error code 1

Stop.
mk: ape/psh -c 'cd ...  : exit status=rc 2646913: psh 2646915: sh 2646920: 1
```

**Comment by mischief** [comment]
re option 1: the simple fix is to override the default CFLAGS in Plan9/mkfile, e.g. `CFLAGS=`. the default is `-FTVw`, where `-T` turns on type signature checking.

**Comment by mischief** [comment]
with this final change, i've passed https://github.com/mxstbr/markdown-test-file/blob/master/TEST.md through discount markdown's stdin and read the resulting html file. looks good :-)

**Comment by mischief** [comment]
also, all tests pass.

**Comment by Orc** [comment]
So I'll need to fix the incompatible prototypes you've found (because @DWORD@ is not likely to always be an int -- discount will probably not work on a PDP-11, but if it did it would blow up because a pdp-11 int is only 16 bits and I'd get wild flag overflow there) no matter what.

**Comment by Orc** [comment]
They void <-> Document aliasing is _EVERYWHERE_, so I'm not sure if a determined effort to void pointer everything in discount,  and cast the eff out of things would work well (or, even if it did,  whether it would expose me to hours of fun if the internal interfaces drift at all.)   So what I did instead is I tweaked the configuration process to test the C compiler with a two-file program where a function is externally declared with a void* argument, but defined with a char* argument.

This appropriately fails on plan9 when (after I add -T to the definition for CC in mkfile) configure.sh is checking to see if the compiler works, and fails to fail if -T isn't there.   So with that it mind I'm going to say it's about as good as I can get without a fairly messy rearrangement of of the code and close this issue.

**Comment by mischief** [comment]
sorry, but 839ba6142808437df75be18b3c6323e7f310fcd8 still doesn't build.

in Plan9/mkfile, the default CFLAGS is still that of the system, `-FTVw`. the T flag still causes type signature errors.

as the compiler is set to `cc` and plan9 `cc` doesn't understand any of the normal plan 9 c compiler options (`-FTVw` included), Plan9/mkfile should have a line under `CC=cc ...` that says `CFLAGS=` (empty) to reset the option list.

can you apply that change?

**Comment by Orc** [comment]
That's odd about your CFLAGS;  the 9front I set up locally has the default CFLAGS set to nothing.  But it's changed now as you requested.

**Comment by mischief** [comment]
argh. this is my fault :)

the ports system i'm building discount in is essentially a set of mk files, which happen to inherit CFLAGS out of `/sys/src/mkfile.proto`. this ports system then invokes discount's mkfiles, so if discount doesn't set it or include the system mkfiles, it gets it out of the environment.

if you want, back out the change and i can fix that in the port system. but perhaps being explicit is better.

**Comment by Orc** [comment]
Thanks for finding that out, but no, I'm gonna leave it be b/c it have me an excuse to move the pair of defines out of CC and into CFLAGS like they should have been in the first place :-)
