### ISSUE TITLE
autolink should ignore punctuation at the end of a potential URL

### ISSUE THREAD

**Issue by Lekensteyn** [Orc/discount#198]
Reproducer:
```sh
printf '%s\n' 'https://example.com, https://example.com/one,two_three https://example.com/.' |
markdown -f autolink
```

Expected result (reflowed for easier reading):
```html
<p>
<a href="https://example.com">https://example.com</a>,
<a href="https://example.com/one,two_three">https://example.com/one,two_three</a>
<a href="https://example.com/">https://example.com/</a>.
</p>
```

Actual result:
```html
<p>
<a href="https://example.com,">https://example.com,</a>
<a href="https://example.com/one,two_three">https://example.com/one,two_three</a>
<a href="https://example.com/.">https://example.com/.</a>
</p>
```

Further information:
The above shows `,` and `.` as characters, but the problem also applies to characters like `?` and `!`.

The autolink behavior defined by CommonMark is different (https://spec.commonmark.org/0.28/#autolink) as it requires URLs to be enclosed by `<` and `>`, but I am looking for GFM compatibility: https://github.github.com/gfm/#autolinks-extension-

**Comment by Orc** [comment]
Those are legal characters in a url, though.   `<`...`>` quoting is the standard way of dealing with urls that bleed into text.

**Comment by Lekensteyn** [comment]
These are indeed valid characters, that why I included the second test case. Markdown is supposed to be more human-friendly, and in the autolinks extension in GFM is a natural interpretation.

It also describes an extension I have not thought of:
> echo 'Doc (https://en.wikipedia.org/wiki/Vim_(text_editor))' | markdown -f autolink

is currently parsed as:
```html
<p>Doc (<a href="https://en.wikipedia.org/wiki/Vim_">https://en.wikipedia.org/wiki/Vim_</a>(text_editor))</p>
```
while this would be more natural:
```html
<p>Doc (<a href="https://en.wikipedia.org/wiki/Vim_(text_editor)">https://en.wikipedia.org/wiki/Vim_(text_editor)</a>)</p>
```

**Comment by Orc** [comment]
Autolinks are already a bit of a kludge;  properly handling `(link with ()s)` to pull `link with()s` out adds an additional layer of assumptions about the structure of the document & the links that doesn't make it any less kludgy :-(

**Comment by Lekensteyn** [comment]
I agree that `(` and `)` are quite complex cases, I suppose that handling punctuation like `,`, `.`, etc. would be a good start. Currently I workaround it by using `<` and `>` as required by Markdown.

**Comment by Orc** [comment]
I've let this mill around in my head for a while, and I can't think of any way to do it the way you want without a _lot_ of logic to try and guess the format of the url.  So I'm going to just close this, sorry.
