### ISSUE TITLE
Support for code syntax highlighting

### ISSUE THREAD

**Issue by kupiqu** [Orc/discount#203]
Would you please consider adding support for code syntax highlighting?

This is an example of this in markdown-here:

![image](https://user-images.githubusercontent.com/3875196/55809642-46cd8d00-5ab4-11e9-9aff-093a3aee4620.png)

**Comment by kupiqu** [comment]
Kmail dev did not reply yet, but I would say that "a code block callback so that an external function could apply syntax highlighting" would be great. 

I suppose Kmail would then be able to apply highlighting as Kate (the KDE Advanced Text Editor).

Thanks

**Comment by kupiqu** [comment]
FYI, Kmail dev reply: "It's not necessary to use kpart. We have a lib for my highlighting. For sure if we have a code block callback I will be able to highlight it."

It would be great if you could implement this feature!

**Comment by Orc** [comment]
Okay, round one (in the new branch `codefmt`) -- I've added in a new callback routine for external formatting, in the form

    char *e_code_fmt(char *codeblock, int codeblock_length, char *class)
    void mkd_e_codefmt(MMIOT *fd, mkd_callback_t formatter);

Where `codeblock` is a string (of `codeblock_length`) that points to the original code block.  `class` is the class given on the initial codeblock line (or null if it's not set.)

`e_code_fmt()` leaves `codeblock` alone & returns a pointer to the formatted codeblock  (if you set a deallocator with `mkd_e_free()`, discount will use that to deallocate the formatted codeblock when it's done with it.   **Warning**:  discount won't do any entity escaping on the formatted block, so the formatter needs to entityify any `<`, `>`, and `&` found in the original codeblock.


I _implemented_ this code this morning, but haven't actually tested it yet.  I'm going to test it, but until then my usual warnings about exploding computers and radiation hazards apply.

**Comment by Orc** [comment]
And this morning I finally wrote and checked in some code to test this feature out.  (In the markdown program (`main.c`); the `-X` option, which passes code blocks through the function `external_codefmt()`)

"It Works For Me"(tm) -- can the Kmail crew check it out for nontrivial external formatting (I don't do any syntax highlighting in my little test callback, I just wanted to make certain it works)?

**Comment by kupiqu** [comment]
> "It Works For Me"(tm)

Great!

> can the Kmail crew check it out for nontrivial external formatting (I don't do any syntax highlighting in my little test callback, I just wanted to make certain it works)?

I'll let them know, thank you!

**Comment by Orc** [comment]
Ugh.  And it appears that I actually checked all the changes into the master branch instead of the codefmt branch.  Ugh.

**Comment by kupiqu** [comment]
> And it appears that I actually checked all the changes into the master branch instead of the codefmt branch. Ugh.

Oops, are you going to reverse it? Should I wait?

**Comment by Orc** [comment]
No, just (sigh) work out of the master branch instead of the codefmt branch; it's a pain to reshuffle branches so I'm just going to leave it as is.

**Comment by kupiqu** [comment]
I have asked the Kmail dev. Let's hope he can give it a try soon...

In the meantime, I tested it myself. Of course I cannot really see any highlighting as Kmail still needs to add support for it, but at least I could check that the library is fully functional.

**Comment by kupiqu** [comment]
FYI: Kmail dev is going to test it next week...

**Comment by Montel** [comment]
Hi,
I am the kmail dev which implemented it.
Just a question:
char *
external_codefmt(char *src, int len, char *lang)

How we define "lang" ?

Regard

**Comment by Orc** [comment]
It's the language tag at the end of the opening fence (if set, otherwise it's a null)

**Comment by kupiqu** [comment]
I think this is working fine in Kmail now (dev version). Should we close this issue?
