### ISSUE TITLE
MKD_ flag for enabling GitHub task lists

### ISSUE THREAD

**Issue by kupiqu** [Orc/discount#205]
Having this option would be a very nice add for users of projects such as Kmail, so they do not need to compile discount themselves.

Kmail dev would be willing to add the setting to Kmail if such an option is made available.

The only issue I see is that there are three cases: `disabled` / `enabled no input` / `enabled input`.

Is this sth a single flag can manage?

[Discussion started in issue #187]

**Comment by Orc** [comment]
It wouldn't fit into a 1-bit flag, so I'd have to either leave it as a compile option or completely redo the flags interface (which is a whole big bag of ouch all by itself.)

**Comment by kupiqu** [comment]
Yes, right. That's unfortunate.

**Comment by kupiqu** [comment]
> It wouldn't fit into a 1-bit flag, so I'd have to either leave it as a compile option or completely redo the flags interface (which is a whole big bag of ouch all by itself.

For Kmail having just `disabled / enabled with input` would be fine, but that is clearly not ideal in general...

**Comment by Orc** [comment]
There's a new branch (v3) that has github checklists as a runtime switch (default enabled, MKD_NORMAL_LISTITEM to disable it)

**Comment by kupiqu** [comment]
Excellent, thank you. I'm checking it out

**Comment by kupiqu** [comment]
It seems --github-checkbox=input is default (isn't it?), which is good given that --github-checkbox=entity looks ugly in comparison (bigger square).

I guess, and hope, this branch will be eventually merged to master :)

**Comment by Orc** [comment]
github-checkbox=entity is the default, because that's what the person who requested the feature in the first place preferred.

**Comment by kupiqu** [comment]
Mmm, this is how it looks by default (I added `margin-left: -1.5em;` to align checkboxes with dots):

![image](https://user-images.githubusercontent.com/3875196/56139226-770aa500-5f66-11e9-9e47-f8ce7b531666.png)

which is the same as with `--github-checkbox=input`

This is how it looks when I explicitly set it to entity:

![image](https://user-images.githubusercontent.com/3875196/56139315-9f929f00-5f66-11e9-8001-17147251bc27.png)

**Comment by Orc** [comment]
Oh, I must have messed up the parsing of that configuration option in configure.sh.  `¯\_(ツ)_/¯`  I guess `github-checkbox=input` is now the default.

**Comment by kupiqu** [comment]
> Oh, I must have messed up the parsing of that configuration option in configure.sh. `¯\_(ツ)_/¯` I guess `github-checkbox=input` is now the default.

Neat! It looks much better IMO :)

**Comment by kupiqu** [comment]
Should we close this? Also wondering, do you have any plan of when V3 will be released?

**Comment by Orc** [comment]
No, I'd say leave it open for now.   I'm still working on the v3 published interface (trying to decide whether to make a whole new bunch of mkd3_(xxx) functions and #define them to the mkd_(xxx) functions in mkdio.h (so that I keep the older interfaces intact and allow older code to function with
the new libraries) or not.
