### ISSUE TITLE
Blockquotes do not seem to be supported

### ISSUE THREAD

**Issue by kupiqu** [Orc/discount#206]
- Blockquote code:

```
> Blockquotes are very handy in email to emulate reply text.
> This line is part of the same quote.

Quote break.

> This is a very long line that will still be quoted properly when it wraps. Oh boy let's keep writing to make sure this is long enough to actually wrap for everyone. Oh, you can *put* **Markdown** into a blockquote. 
```

- Expected result:

> Blockquotes are very handy in email to emulate reply text.
> This line is part of the same quote.

Quote break.

> This is a very long line that will still be quoted properly when it wraps. Oh boy let's keep writing to make sure this is long enough to actually wrap for everyone. Oh, you can *put* **Markdown** into a blockquote. 

- Observed result:

![image](https://user-images.githubusercontent.com/3875196/56132018-f6907800-5f56-11e9-88e6-4679108d01b8.png)

**Comment by Orc** [comment]
I don't see what's not working here??

**Comment by kupiqu** [comment]
Let me separate it:

1. Observed result:

![image](https://user-images.githubusercontent.com/3875196/56132018-f6907800-5f56-11e9-88e6-4679108d01b8.png)

**Comment by kupiqu** [comment]
2. Expected result:

> Blockquotes are very handy in email to emulate reply text.
> This line is part of the same quote.

Quote break.

> This is a very long line that will still be quoted properly when it wraps. Oh boy let's keep writing to make sure this is long enough to actually wrap for everyone. Oh, you can *put* **Markdown** into a blockquote.

**Comment by Orc** [comment]
Oh, I see, you're confusing github-flavored markdown with standard markdown.

If you want to emulate github behavior where line breaks carry through to the html, you need to use the `gfm_` methods to read the source in (`-G` in the markdown program; `gfm_in()`, `gfm_string()`, and `gfm_populate()` when you're using the library.)

**Comment by kupiqu** [comment]
> Oh, I see, you're confusing github-flavored markdown with standard markdown.
> 
> If you want to emulate github behavior where line breaks carry through to the html, you need to use the `gfm_` methods to read the source in (`-G` in the markdown program; `gfm_in()`, `gfm_string()`, and `gfm_populate()` when you're using the library.)

I see. Two things:

1. How can I do the same with mkd2html ?

2. Is there a way to have the same github style ? I guess this also requires tuning a css file, doesn't it?

**Comment by kupiqu** [comment]
> 2. Is there a way to have the same github style ? I guess this also requires tuning a css file, doesn't it?

I confirm this (I found some css files for github and work as expected).
