### ISSUE TITLE
adding support for different styles ?

### ISSUE THREAD

**Issue by kupiqu** [Orc/discount#207]
This could be in general, but one particular example of this could be tables. 

Tables in markdown here look very nice:

![image](https://user-images.githubusercontent.com/3875196/56132518-2be99580-5f58-11e9-90bc-b2979cbcd795.png)

I wonder if one can get different table styles (including the one above), e.g. using some css code or sth.

**Comment by kupiqu** [comment]
Table style in Github is similar to Markdown here:

- Tables code:
```
Colons can be used to align columns.

| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |

There must be at least 3 dashes separating each header cell.
The outer pipes (|) are optional, and you don't need to make the 
raw Markdown line up prettily. You can also use inline Markdown.

Markdown | Less | Pretty
--- | --- | ---
*Still* | `renders` | **nicely**
1 | 2 | 3
```

- Expected result:

Colons can be used to align columns.

| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |

There must be at least 3 dashes separating each header cell.
The outer pipes (|) are optional, and you don't need to make the 
raw Markdown line up prettily. You can also use inline Markdown.

Markdown | Less | Pretty
--- | --- | ---
*Still* | `renders` | **nicely**
1 | 2 | 3

- Observed result:

![image](https://user-images.githubusercontent.com/3875196/56132886-2d678d80-5f59-11e9-8d31-da83f18f6267.png)

**Comment by kupiqu** [comment]
Perhaps emulating Github would be enough. It's a nice style.

**Comment by Orc** [comment]
You need to build your own css to style the tables to look more like the github implementation; that's not really in discount's wheelhouse.

**Comment by kupiqu** [comment]
> You need to build your own css to style the tables to look more like the github implementation; that's not really in discount's wheelhouse.

I see, thank you for the info. I understand now that this is not part of Discount (but perhaps it would be nice to consider adding an example of a css file, e.g., github.css style to help final users).

**Comment by kupiqu** [comment]
> perhaps it would be nice to consider adding an example of a css file, e.g., github.css style to help final users

nevermind, it is very easy to get one from the internet (although one needs to add the github checkbox style thing as indicated in #187).

**Comment by kupiqu** [comment]
Could you please let me know how to let the discount library know about the desired css style  to be applied? That is especially important for projects such as Kmail (who asked about it).

**Comment by kupiqu** [comment]
May it be using the following function?

`int mkd_css(MMIOT *doc, char **out)` allocates a buffer and populates it with any style blocks found in the document.

Could you please confirm?

**Comment by Orc** [comment]
Discount sweeps up `<style>` blocks (unless you set MKD_NOSTYLE, which I presume is not being done here) and returns them, yes.   But style blocks go in the header section of a html document, so the way that the markdown program (main.c) does it is a good reference:

~~~~
            if ( mkd_compile(doc, flags) ) {
                if ( styles )
                    mkd_generatecss(doc, stdout);
               if ( content )
                    mkd_generatehtml(doc, stdout);
           }
~~~~

(With, of course, the caveat that the style blocks go in the header of the document)

**Comment by kupiqu** [comment]
Mmm... unfortunately, I think having to add all styles (e.g., github.css set of styles) in the header of each email body is not going to be feasible for Kmail :(

Would there be a way to add the possibility to get all that from an external css file as in mkd2html? If so, could you please consider implementing that option?

That would be highly appreciated, as it would then be very easy to set the style in Kmail settings and regular users would not have to worry about it (plus advanced users could easily change styles between e.g., github, markdown-here, and plain markdown, very easily, just replacing the css file in settings.

**Comment by Orc** [comment]
That would be a kmail feature, not a discount feature.

**Comment by kupiqu** [comment]
I see, thanks for the info.

[Just to be crystal clear: I meant about the possibility to implement an option to pass a css file to the library. The rest is indeed something in Kmail's end, but I added so you could see why this could be useful. But I guess you understood what I meant and still think this must be set in Kmail]

**Comment by Orc** [comment]
You can't sensibly pass a css file to the library, because non-inline css is handled in the document header and markdown formats the contents of the document body.

**Comment by kupiqu** [comment]
Thanks for clarifying this to me :)
