### ISSUE TITLE
mkd2html output filename does not seem to work

### ISSUE THREAD

**Issue by kupiqu** [Orc/discount#208]
I run: `mkd2html test.md test_alt.html` and the output file is `test.html` instead of `test_alt.html`

**Comment by Orc** [comment]
Definitely a bug.   Fixed (and I also added the `-G` option to mkd2html so it will treat the input as github flavored markdown.)

**Comment by kupiqu** [comment]
Great, thanks!

**Comment by Orc** [comment]
Please test it out and let me know if it works, then I can close out this bug!

**Comment by kupiqu** [comment]
It does

**Comment by kupiqu** [comment]
Also `-G` option works as expected :)
