### ISSUE TITLE
There is a problem with the fencedcode of version 2.2.5

### ISSUE THREAD

**Issue by lddfg** [Orc/discount#209]
First of all, thank you for your contribution. The problem is described as follows:

version: `2.2.5`
cmd: `markdown -ffencedcode mk.md`
Document content:
````
Before the code

```python

import multiprocessing
import time
def func(number):
    for i in range(1, 10):
        time.sleep(0.01)
        print('Processing ' + str(number) + ': prints ' + str(number*i))

```

Between codes

```python

import multiprocessing
import time

for i in range(0, 3):
    process = multiprocessing.Process(target=func, args=(i,))

```

After the code

````

cmd output:
````
<pre><code class="python">
import multiprocessing
import time
def func(number):
    for i in range(1, 10):
        time.sleep(0.01)
        print('Processing ' + str(number) + ': prints ' + str(number*i))
</code></pre>

<pre><code class="python">
import multiprocessing
import time

for i in range(0, 3):
    process = multiprocessing.Process(target=func, args=(i,))
</code></pre>

<p>Before the code</p>

<p>Between codes</p>

<p>After the code</p>
````

I think I should fall back to 2.2.4, but I am still troubled by the #202 problem.
I look forward to your reply. If I have forgotten anything, please correct me. Thank you again for your hard work.

**Comment by Orc** [comment]
I'd fixed that bug, but didn't tag the release because I was working in a different branch.

I've fixed it; try the latest version here on github (v2.2.6) and tell me if it fixes your problem.

**Comment by lddfg** [comment]
Ok, I will try this.
Thank you again for your work.

**Comment by worldofpeace** [comment]
With the latest version the output of the command is
```
<p>Before the code</p>

<pre><code class="python">
import multiprocessing
import time
def func(number):
    for i in range(1, 10):
        time.sleep(0.01)
        print('Processing ' + str(number) + ': prints ' + str(number*i))
</code></pre>

<p>Between codes</p>

<pre><code class="python">
import multiprocessing
import time

for i in range(0, 3):
    process = multiprocessing.Process(target=func, args=(i,))
</code></pre>

<p>After the code</p>
```

And this appears to be correct to me.

**Comment by lddfg** [comment]
Yes, the latest 2.2.6 version works fine. I am really sorry, these days are too busy to respond in time.
Maybe look for a `TODO` software to help record some unfinished things for myself.
**Thanks again!**
