### ISSUE TITLE
Better usage with LaTeX

### ISSUE THREAD

**Issue by mmmm1998** [Orc/discount#211]
I use Discount in my app with added LaTeX math support and I see a few difficulties with using LaTeX in this moment:
  1) No support for $...$ (only for $$...$$). So, could parser handle $...$ like it do with $$...$$? If it's not very difficult, I think, I could try to write pull request for it (with new option for this, I think).
  2) Problem with calculation position of $$...$$ blocks. I mean, I can't just use regexp for `$$` because the dollar sign could be inside ` block or code block. And parsing input text or rendered markdown for getting only needed $$...$$ looks overhead for me here, because we already have parser in the library.

For second problem, maybe will be usefull callback for content of $$...$$ (like `mkd_e_url`) or maybe function for processing MMIOT and returning positions of all math blocks.

So, @Orc, that are you think about it? Maybe I missed something? Also, I hope, you could give me a assessment of  complexity of this changes, because you more familiar with code, that me (i am thinking about writing pull request by myself).

**Comment by Orc** [comment]
What's the difference between $...$ vs $$...$$ ? 

If I was going to do a callback handler, it would be a new mkd_e_latex (that is called by generate.c:mathhandler) one.   I wouldn't want to build a markup tree that points back into the generated html, because that way lies madness (not in making the markup tree, but in the possibility of all sorts of exciting defects with recalculating pointers into the block of code.)

**Comment by mmmm1998** [comment]
There are difference in latex meaning ($...$ for inline math, $$...$$ displayed math).
For library, I think, there aren't difference, but $...$ more widely used, that $$...$$, for example MathJax support $, etc.

For my task, supporting will be very usefull, because i got markdown with $...$
And I need to convert this $ to $$, which need parsing the markdown.

**Comment by Orc** [comment]
mathhandler() is set up for 2-character delimiters only, so a single-character escape function would be needed for a single-character delimited version (and that might collide horribly with using $ for US currency?)     Are they any constraints on single-$ delimiters (like requiring whitespace around them) or is it just if you run into a $ whoops you're in LaTeX until the next $ ?

**Comment by mmmm1998** [comment]
Yes, if you use $ as math delimiter, for using $ as dollar, you need do escaping, like `It costs 12\$ and this costs 15\$` (and it should be render as `It costs 12$ and this costs 15$`)

**Comment by Orc** [comment]
So doing something like "thisisalongword$with latex inside it, oh the joy!$indeed" is how it's done, or is it "thisisalongword $ with latex after it $ indeed" or "thisisalongword$ with latex inside it $indeed" ?

**Comment by mmmm1998** [comment]
Second variant (and for this reason i suppose new flag because of backward behaviour compability)

**Comment by Orc** [comment]
Oh, if it's a mandatory 2-character delimiter ($\<space> & \<space>$) it's a _lot_ easier to do.

~~~~
diff --git a/generate.c b/generate.c
index 30acb64..d711c3a 100644
--- a/generate.c
+++ b/generate.c
@@ -1486,11 +1486,21 @@ text(MMIOT *f)
 			Qchar(c, f);
 		    break;
 
-	case '$':   if ( is_flag_set(f->flags, MKD_LATEX) && (peek(f, 1) == '$') ) {
-			pull(f);
-			if ( mathhandler(f, '$', '$') )
-			    break;
-			Qchar('$', f);
+	case '$':   if ( is_flag_set(f->flags, MKD_LATEX) ) {
+
+			if ( (peek(f, 1) == '$') ) {
+			    pull(f);
+			    if ( mathhandler(f, '$', '$') )
+				break;
+			    Qchar('$', f);
+			}
+			else if (peek(f,1) == ' ') ) {
+			    pull(f);
+			    if ( mathhandler(f, ' ', '$') )
+				break;
+			    Qchar('$');
+			}
+		    
 		    }
 		    /* fall through to default */
 	
~~~~

**Comment by mmmm1998** [comment]
It's for 2-character delimiter `$<space>`...`<space>$`, right? Because the delimiter `$` is 1-character.
For example:
````
$\Gamma$
$\sqrt{3} \cdot \frac{2}{15}$
````

**Comment by Orc** [comment]
So the text fragment "thisisalong$\Gamma$word" should legitimately stuff the LaTeX Gamma into the middle of this word, yes?

**Comment by mmmm1998** [comment]
Yes, it will be look something like this <a href="https://www.codecogs.com/eqnedit.php?latex=\large&space;\mathrm{thisisalong}$\Gamma$\mathrm{word}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\large&space;\mathrm{thisisalong}$\Gamma$\mathrm{word}" title="\large \mathrm{thisisalong}$\Gamma$\mathrm{word}" /></a>

**Comment by Orc** [comment]
So, like:

~~~~
diff --git a/generate.c b/generate.c
index 30acb64..bdfd0fd 100644
--- a/generate.c
+++ b/generate.c
@@ -1486,11 +1486,27 @@ text(MMIOT *f)
 			Qchar(c, f);
 		    break;
 
-	case '$':   if ( is_flag_set(f->flags, MKD_LATEX) && (peek(f, 1) == '$') ) {
-			pull(f);
-			if ( mathhandler(f, '$', '$') )
-			    break;
-			Qchar('$', f);
+	case '$':   if ( is_flag_set(f->flags, MKD_LATEX) ) {
+			if (peek(f, 1) == '$' ) {
+			    pull(f);
+			    if ( mathhandler(f, '$', '$') )
+				break;
+			    Qchar('$', f);
+			}
+			else {
+			    int c2;
+			    int i = 1;
+
+			    while ( ((c2=peek(f,i)) != '$') && (c2 != EOF) )
+				i++;
+
+			    if ( c2 != EOF ) {
+				Qchar('$', f);
+				while (i-- > 0 )
+				    Qchar(pull(f), f);
+				break;
+			    }
+			}
 		    }
 		    /* fall through to default */
 	
~~~~

**Comment by mmmm1998** [comment]
Looks nice, i will test this and respond about the results here.

**Comment by mmmm1998** [comment]
The code have passed all syntax tests ([input.txt](https://github.com/Orc/discount/files/3307984/input.txt)) which I came up with, so I think all fine.
But what about using dollar not as math (for example, using as dollar sign in a cost)?
For example, 
`It costs 16\$ *and* 12\$` I think, should be `<p>It costs 16$ <em>and</em> 12$</p>` and not `<p>It costs 16\$ *and* 12\$</p>`

**Comment by Orc** [comment]
Yeah, it was a q&d patch.  To make it fully work I needed to revise the way escaping works (and take out a couple of tests that checked for the absence of single-character LaTeX escapes):

~~~~
diff --git a/generate.c b/generate.c
index 30acb64..f54b789 100644
--- a/generate.c
+++ b/generate.c
@@ -1459,8 +1459,14 @@ text(MMIOT *f)
 		    case '(':   if ( is_flag_set(f->flags, MKD_LATEX)
 				   && mathhandler(f, '\\', (c =='(')?')':']') )
 				    break;
-				/* else fall through to default */
+				Qchar(c, f);
+				break;
 			
+		    case '$':	if ( is_flag_set(f->flags, MKD_LATEX) ) {
+				    Qchar(c, f);
+				    break;
+				}
+				
 		    default:    if ( escaped(f,c) ||
 				     strchr(">#.-+{}]![*_\\()`", c) )
 				    Qchar(c, f);
@@ -1486,11 +1492,27 @@ text(MMIOT *f)
 			Qchar(c, f);
 		    break;
 
-	case '$':   if ( is_flag_set(f->flags, MKD_LATEX) && (peek(f, 1) == '$') ) {
-			pull(f);
-			if ( mathhandler(f, '$', '$') )
-			    break;
-			Qchar('$', f);
+	case '$':   if ( is_flag_set(f->flags, MKD_LATEX) ) {
+			if (peek(f, 1) == '$' ) {
+			    pull(f);
+			    if ( mathhandler(f, '$', '$') )
+				break;
+			    Qchar('$', f);
+			}
+			else {
+			    int c2;
+			    int i = 1;
+
+			    while ( ((c2=peek(f,i)) != '$') && (c2 != EOF) )
+				i++;
+
+			    if ( c2 != EOF ) {
+				Qchar('$', f);
+				while (i-- > 0 )
+				    Qchar(pull(f), f);
+				break;
+			    }
+			}
 		    }
 		    /* fall through to default */
 	
diff --git a/tests/latex.t b/tests/latex.t
index 3df811e..c62e7da 100644
--- a/tests/latex.t
+++ b/tests/latex.t
@@ -10,13 +10,13 @@ try -flatex 'latex w/ \( .. \) and link inside' '\([(1+2)*3-4](1-2)\)' '<p>\([(1
 try -flatex 'latex w/ \( .. \) and special characters' 'Equation:\(a<+>b\).' \
     '<p>Equation:\(a&lt;+&gt;b\).</p>'
 
-try -flatex 'latex $ delimiter not supported' '$[a](b)$' '<p>$<a href="b">a</a>$</p>'
+#try -flatex 'latex $ delimiter not supported' '$[a](b)$' '<p>$<a href="b">a</a>$</p>'
 
 try -flatex 'latex with $$ .. $$' '$$foo$$' '<p>$$foo$$</p>'
 try -flatex 'latex with $$ .. $$ like a link' '$$[(1+2)*3-4](1-2)$$' '<p>$$[(1+2)*3-4](1-2)$$</p>'
 try -flatex 'latex with multiple $$ .. $$' '$$[a](b)$$$$[a](b)$$' '<p>$$[a](b)$$$$[a](b)$$</p>'
 try -flatex 'latex with $$ .. $$ and a real link' '$$[a](b)$$[a](b)$$' '<p>$$[a](b)$$<a href="b">a</a>$$</p>'
-try -flatex 'latex with $$ .. $$ and a real link' '$$[a](b)$$$[a](b)$$' '<p>$$[a](b)$$$<a href="b">a</a>$$</p>'
+#try -flatex 'latex with $$ .. $$ and a real link' '$$[a](b)$$$[a](b)$$' '<p>$$[a](b)$$$<a href="b">a</a>$$</p>'
 try -flatex 'latex with $$ .. $$ multi lines' '$$\begin{split}\nabla \times \vec{\mathbf{B}} -\, \frac1c\, \frac{\partial\vec{\mathbf{E}}}{\partial t} & = \frac{4\pi}{c}\vec{\mathbf{j}} \\   \nabla \cdot \vec{\mathbf{E}} & = 4 \pi \rho \\ \nabla \times \vec{\mathbf{E}}\, +\, \frac1c\, \frac{\partial\vec{\mathbf{B}}}{\partial t} & = \vec{\mathbf{0}} \\ \nabla \cdot \vec{\mathbf{B}} & = 0 \end{split}$$' '<p>$$\begin{split}\nabla \times \vec{\mathbf{B}} -\, \frac1c\, \frac{\partial\vec{\mathbf{E}}}{\partial t} &amp; = \frac{4\pi}{c}\vec{\mathbf{j}} \\   \nabla \cdot \vec{\mathbf{E}} &amp; = 4 \pi \rho \\ \nabla \times \vec{\mathbf{E}}\, +\, \frac1c\, \frac{\partial\vec{\mathbf{B}}}{\partial t} &amp; = \vec{\mathbf{0}} \\ \nabla \cdot \vec{\mathbf{B}} &amp; = 0 \end{split}$$</p>'
 
 try -flatex 'latex with \[ .. \]' '\[foo\]' '<p>\[foo\]</p>'
~~~~

**Comment by mmmm1998** [comment]
Very good, do you plan to add this to master?

**Comment by Orc** [comment]
Whoops, I forgot to close this after pushing the changes in.  Sorry!

**Comment by mmmm1998** [comment]
Hi, @Orc , it was quite a while since last we have spoken, so I hope you are doing well.
I would like to revisit this discussion and its status - as far as I understand, at the moment, Discount library is not supporting single `$` LaTeX expressions (example would be `$ 2 + 2 $`), right? I mean, as far as I can see - this "quick and dirty" patch from above eventually haven't been polished and merged in the main branch of the implementation (generate.c), and my PR (#214) was closed as rejected (not merged).
Is this understanding correct?

**Comment by Orc** [comment]
...

Um, I thought I'd merged that or written similar functionality.    My fault -- I was preoccupied when I went through and swept out what I thought were resolved and/or dangling issues.


Sigh.

So `$ <expression> $`  is just a fancy code span like the other LaTeX escapes, right (fancy code span == don't process the code, but don't add  the regular code span decorations)?

I think it might be possible to subvert the emphasis/codespan code to handle this without much fuss ... (type type type) ...  yes, the tickhandler() function is a somewhat more readable first pass.

So, sorry again;  hopefully the latest push makes the code do what you need now?

**Comment by mmmm1998** [comment]
> Um, I thought I'd merged that or written similar functionality. My fault -- I was preoccupied when I went through and swept out what I thought were resolved and/or dangling issues.

Ah, I see, well, we could do it now, I think.

> So $ <expression> $ is just a fancy code span like the other LaTeX escapes, right (fancy code span == don't process the code, but don't add the regular code span decorations)?

If I understood you correctly, then yes.

> I think it might be possible to subvert the emphasis/codespan code to handle this without much fuss ... (type type type) ... yes, the tickhandler() function is a somewhat more readable first pass.
> So, sorry again; hopefully the latest push makes the code do what you need now?

It is close, thanks! But I have spotted a problem here. It looks like there is a bug, because the first symbol right after `$` is lost, which shouldn't happen.

For example, this input:
`$ ./markdown -flatex -s '$\delta$ $\Gamma$'`

Expected result in HTML form here would be this: `<p>$\delta$ $\Gamma$</p>` which is $\delta$ $\Gamma$

But currently produced result from the top of the main branch is this: `<p>$delta$ $Gamma$</p>` (missing `\` right after first `$`) which is looks like this $delta$ $Gamma$ and this is quite different result from the expected as you can see.

**Comment by Orc** [comment]
In the grand tradition of quick & dirty!

(I'd eyeballed it with '$ foo $' and of course eating the first character there didn't matter.   I went back and looked at the other span handlers and they'd all set the start of the span to `cursor()-1`, and now I've pushed a change to the mirror to correct the LaTeX span handler.)

**Comment by mmmm1998** [comment]
*> (I'd eyeballed it with '$ foo $' and of course eating the first character there didn't matter. I went back and looked at the other span handlers and they'd all set the start of the span to cursor()-1, and now I've pushed a change to the mirror to correct the LaTeX span handler.)*

Thanks, @Orc! Although, I have run more complex tests and it looks like some modifications are still required. I revisited the tests we discussed 5 years ago at the beginning of this GitHub issue, and I have gotten list of the possible tests like this:

````
diff --git a/tests/latex.t b/tests/latex.t
index 380502b..00d5d3d 100644
--- a/tests/latex.t
+++ b/tests/latex.t
@@ -24,6 +24,18 @@ try -flatex 'latex with \[ .. \] and link inside' '\[[(1+2)*3-4](1-2)\]' '<p>\[[
 try -flatex 'latex with \[ .. \] multi lines' '\[\begin{split}\nabla \times \vec{\mathbf{B}} -\, \frac1c\, \frac{\partial\vec{\mathbf{E}}}{\partial t} & = \frac{4\pi}{c}\vec{\mathbf{j}} \\   \nabla \cdot \vec{\mathbf{E}} & = 4 \pi \rho \\ \nabla \times \vec{\mathbf{E}}\, +\, \frac1c\, \frac{\partial\vec{\mathbf{B}}}{\partial t} & = \vec{\mathbf{0}} \\ \nabla \cdot \vec{\mathbf{B}} & = 0 \end{split}\]' '<p>\[\begin{split}\nabla \times \vec{\mathbf{B}} -\, \frac1c\, \frac{\partial\vec{\mathbf{E}}}{\partial t} &amp; = \frac{4\pi}{c}\vec{\mathbf{j}} \\   \nabla \cdot \vec{\mathbf{E}} &amp; = 4 \pi \rho \\ \nabla \times \vec{\mathbf{E}}\, +\, \frac1c\, \frac{\partial\vec{\mathbf{B}}}{\partial t} &amp; = \vec{\mathbf{0}} \\ \nabla \cdot \vec{\mathbf{B}} &amp; = 0 \end{split}\]</p>'
 
 try -flatex 'latex with $ .. $' '$foo$' '<p>$foo$</p>'
+try -flatex 'latex with asterisks inside $ .. $' '$*foo*$' '<p>$*foo*$</p>'
+try -flatex 'latex with asterisks inside $ .. $ with space' ' $ *foo* $ ' '<p> $ *foo* $</p>'
+try -flatex 'latex with asterisks inside escaped latex $ .. $' '\$*foo*\$' '<p>$<em>foo</em>$</p>'
+try -flatex 'latex with asterisks inside latex $ .. $ inside code segment' '`$ *foo* $`' '<p><code>$ *foo* $</code></p>'
+try -flatex 'latex with asterisks inside latex $ .. $ inside code segment' '`$ *foo* $`' '<p><code>$ *foo* $</code></p>'
+try -flatex 'Bold text inside unfinished latex $$ .. $$' '$$*foo*' '<p>$$<em>foo</em></p>'
+try -flatex 'Bold text inside unfinished latex $ .. $' '$*foo*' '<p>$<em>foo</em></p>'
+try -flatex 'Bold text inside sequence of latex $ .. $' '$*foo*$$*foo*$$*foo*$' '<p>$*foo*$$*foo*$$*foo*$</p>'
+try -flatex 'Bold text inside sequence of latex $$ .. $$' '$$*foo*$$$$*foo*$$$$*foo*$$' '<p>$$*foo*$$$$*foo*$$$$*foo*$$</p>'
+try -flatex 'Bold text inside sequence of latex $ .. $ and $$ .. $$' '$*foo*$$$*foo*$$*foo*' '<p>$*foo*$$$*foo*$$<em>foo</em></p>'
+try -flatex 'Bold text inside latex $$ .. $$ and unfinished $ .. $' '$$*foo*$$$*foo*' '<p>$$*foo*$$$<em>foo</em></p>'
+try -flatex 'Bold text inside and around latex unfinished $$ .. $$ and not started $ .. $' '*foo*$$*foo*$*foo*' '<p><em>foo</em>$$<em>foo</em>$<em>foo</em></p>'
 
 summary $0
 exit $rc
````

Some of these tests are passing, but others are indicating a few problems:

````
check flag functions: set set(0) clear clear(0) copy copy(0) ok
headers ... GOOD
Reddit-style automatic links ................................... OK
automatic links ................................................ OK
backslash escapes .............................................. OK
callbacks ...................................................... OK
block centering ................................................ OK
inline code .................................................... OK
traditional code blocks ........................................ OK
fenced code blocks ............................................. OK
markdown 1.0 compatibility ..................................... OK
crashes ........................................................ OK
reported defects ............................................... OK
%div% blocks ................................................... OK
definition lists ............................................... OK
emphasis ....................................................... OK
markdown extra-style footnotes ................................. OK
paragraph flow ................................................. OK
footnotes ...................................................... OK
github tags .................................................... OK
headers ........................................................ OK
html blocks .................................................... OK
html5 blocks (mkd_with_html5_tags) ............................. OK
html comments .................................................. OK
embedded latex .................................................
latex with asterisks inside escaped latex $ .. $
source:
        \$*foo*\$
diff:
        1c1
        < <p>$<em>foo</em>$</p>
        ---
        > <p>\$*foo*\$</p>

Bold text inside unfinished latex $$ .. $$
source:
        $$*foo*
diff:
        1c1
        < <p>$$<em>foo</em></p>
        ---
        > <p>$$foo*</p>

Bold text inside sequence of latex $ .. $ and $$ .. $$
source:
        $*foo*$$$*foo*$$*foo*
diff:
        1c1
        < <p>$*foo*$$$*foo*$$<em>foo</em></p>
        ---
        > <p>$<em>foo</em>$$$*foo*$$<em>foo</em></p>

Bold text inside and around latex unfinished $ .. $ and not started $$ .. $$
source:
        *foo*$$*foo*$*foo*
diff:
        1c1
        < <p><em>foo</em>$$<em>foo</em>$<em>foo</em></p>
        ---
        > <p><em>foo</em>$$foo<em>$</em>foo*</p>

tests/latex.t: 24 tests; 4 failed/20 passed

make: *** [Makefile:140: test] Error 1
````

The first failed test indicates that `$` is now a tick, but escaping is not working correctly. You probably need to check the part of the source code which handles `\*`, `\_`, `\#`, `\``, etc., and add a rule for `$` there as well.

The second failed test indicates that the code hasn’t properly matched `$` at the beginning of the input with the first `$` in the `$$$` section. As far as I understand, this should be possible from a Markdown perspective. However, I could be wrong, and maybe a space is required in this case(like this: `$$$` -> `$ $$`), so feel free to correct me.

Third failed test is a bit ambiguous by itself because there are two interpretations here:
- Markdown should either read such input as unmatched `$$` and unmatched `$`, which would produce `<p><em>foo</em>$$<em>foo</em>$<em>foo</em></p>` as the HTML output.
- Or alternatively, Markdown should read unmatched `$` and then matched `$ .. $`, which would produce `<p><em>foo</em>$$*foo*$<em>foo</em></p>` as the HTML output.

But in the actual output, we are getting a bold `$`, and the asterisk at the beginning of the second "foo" is missing. So, it looks like another case where the library code is losing an input symbol.

**Comment by mmmm1998** [comment]
@Orc , I also have another proposal, in the context of the already ongoing discussion, that I would like to discuss. The proposal is an idea to add new functionality to the library that would allow it to process LaTeX expressions (text inside `$ .. $` and `$$ .. $$`) via some callback or, alternatively, through a method that would return a list of LaTeX expressions in the MMIOT document.

As I understand, the library already has similar functionality (for callback implementation) in the form of mkd_e_url, mkd_e_flags, mkd_e_anchor, and mkd_e_code_format functions. So, the existing code could be mostly reused to add new functionality for LaTeX, possibly under the name mkd_e_latex_format or something similar.

The reason behind this proposal is that while the Discount library is not a TeX/LaTeX preprocessor and can't generate output images from LaTeX input, there are libraries that can do that. This would allow developers and users of the Discount library to, so to speak, "outsource" the generation of LaTeX images to such libraries, and then just inject the generated images into the HTML produced by Discount from Markdown input.

I have a quick and dirty (but fully functional) implementation of this functionality on top of Discount 2.2.6 (a source code of discount from 5 years ago). But now I’m thinking about whether it's possible to merge these changes into upstream (with some modifications, since the library is already at version 3.0.0e and there have been some changes). So, what do you think about this idea? Would you be okay with it if I provided a PR (or maybe you'd even want to write part of it yourself), or do you prefer not to include such functionality in the Discount library?
