### ISSUE TITLE
Use by including in own project

### ISSUE THREAD

**Issue by martinrotter** [Orc/discount#216]
Hello, I plan to use discount with [Textosaurus](https://github.com/martinrotter/textosaurus) and I do not want to compile discount into separate lib. I want to include it directly inside my source (and citing license and respecting it of course).

Question is, what files exactly (and with any modifications?) do I need to include?

**Comment by Orc** [comment]
Have you considered building discount as a static library instead of a shared library?   That will get you away from miscompatibility issues and you won't need to worry about information bleeding around the published interface.

**Comment by martinrotter** [comment]
> Have you considered building discount as a static library instead of a shared library? That will get you away from miscompatibility issues and you won't need to worry about information bleeding around the published interface.

Yes, I did, but I do not generally like the idea of adding extra build-deps to my project (CMake) and while code size of discount is quite small I thought it would be nice to include it directly within my code base.

**Comment by Orc** [comment]
Well, hmm, if you're using cmake I can see how it's a pain to actually add things.

The core of the library is mkdio.c (published interface), markdown.c, and generate.c;  they include things out of different files, so all I can suggest is to try building just those at first and when cmake throws errors just start adding in the files that contain the additional functions needed.

**Comment by martinrotter** [comment]
Textosaurus is Qt-base app and I extensively use qmake, which is therefore preinstalled with Qt on all platforms, besides that, no other real deps exist.
