### ISSUE TITLE
How to match internal links with the destination?

### ISSUE THREAD

**Issue by tsdgeos** [Orc/discount#221]
Hi, we're using discount in Okular to render markdown files, great work!

We recently got a bug about internal links, the user says that it expects that 
```

# TEST LINKS
1. [External link to web site](https://kde.org/)
2. [Local link to file](/etc/hosts)
3. [Internal link to chapter](#Chapter)
<div style="page-break-after: always;">
---end-of-page---
</div>
# Chapter
```

The link in 3 would link to the second page.

The thing is that the HTML we get back from discount is
`<h1>TEST LINKS</h1>\n\n<ol>\n<li><a href=\"https://kde.org/\">External link to web site</a></li>\n<li><a href=\"/etc/hosts\">Local link to file</a></li>\n<li><a href=\"#Chapter\">Internal link to chapter</a></li>\n</ol>\n\n\n<div style=\"page-break-after: always;\">\n---end-of-page---\n</div>\n\n\n<h1>Chapter</h1>`

and there isn't really anything that links that a with href Chapter to the h1 below (other than doing string matching that feels weird.

Are internal links supported in discount? Would it be possible to get the h1 to contain an id so we can match it against the href?

**Comment by Orc** [comment]
Have you/they tried the MKD_TOC flag?  That puts `<a name={heading name}></a>` before every heading.

**Comment by tsdgeos** [comment]
That helps, thanks and sorry for not having read the documentation better :)

**Comment by Orc** [comment]
Oh, don't blame yourself; the documentation is hideously out of date and poorly written.  I'm holding off on releasing version 3 because I'm working on updating the documentation, and it's sitting there *laughing at me* with its awfulness.
