### ISSUE TITLE
MKD_HTML5ANCHOR listed on website, but nowhere else?

### ISSUE THREAD

**Issue by psifertex** [Orc/discount#222]
Is the `MKD_HTML5ANCHOR` option real?

It's listed on the website table of configuration settings, but I find zero references in issues, source, or commits. 

Actually, from: https://github.com/Orc/discount/blob/master/pgm_options.c#L74-L75

maybe the option just got renamed `MKD_URLENCODEDANCHOR` and the website is just outdated?

**Comment by Orc** [comment]
Yes, the documentation is HIDEOUSLY outdated;  I'm working on fixing that right now for the version 3 release.  And, yes, HTML5ANCHOR was stripped out in favor of URLENCODEDANCHOR.

-david parsond

**Comment by Orc** [comment]
I stripped it out because the v1/v2 flags was a 32 bit integer and I was bumping up against the edges of that.   The v3 flags are drastically different, so that will hopefully not be an issue until the flag structure gets so big that it starts exhausting memory.

**Comment by psifertex** [comment]
You'll have other problems at that point. 😉 

Thanks for the quick update.
