### ISSUE TITLE
CMake build broken

### ISSUE THREAD

**Issue by jmccl** [Orc/discount#223]
I get the following after "cmake . && make" in the cmake directory.

[ 81%] Linking C executable markdown
/usr/bin/ld: CMakeFiles/common.dir/home/john/third-party/discount/pgm_options.c.o:(.data.rel+0x28): undefined reference to `___mkd_strict_mode'
collect2: error: ld returned 1 exit status

**Comment by Orc** [comment]
I don't use cmake, so that configuration tends to lag behind the rest of the build.   It looks like it's not building the v2compat module;    Try adding `"${_ROOT}/v2compat.c"` to the `addlibrary(libmarkdown ...` stanza and see if that makes it work for you.

**Comment by jmccl** [comment]
Yes, that fixes it. Thanks for the quick response.

**Comment by jmccl** [comment]
Fixed
