### ISSUE TITLE
Trouble using static library

### ISSUE THREAD

**Issue by jmccl** [Orc/discount#224]
I’ve been using the static library for a number of years now and decided to upgrade to the latest code.

Building with autotools goes smoothly. I changed my code to – I think – deal with the new flags system. My code compiles but won’t link as it can’t find mkd_flag_set (defined in mkdio.h.) 

There seems to be no implementation for that function as well as for a number of functions defined in mkdio.h related to flags.

As near as I can tell the code seems to all set flags using set_mkd_flag defined in markdown.h. That header isn’t installed with ‘make install’ and the implementation suggests it’s supposed to be private to the discount package.

I’m a little lost. Can you point me in the right direction?

**Comment by jmccl** [comment]
defined -> declared

**Comment by Orc** [comment]
No, those functions were renamed mkd_set_flag_num() and mkd_clr_flag_num() (because I've also got a set flags from string & set flags from bitmap) and I managed to forget to strip them out of mkdio.h

**Comment by Orc** [comment]
(The documentation is s-l-o-w-l-y being updated to version 3; I've not formally released v3 yet because it _all_ needs to be rewritten.)

**Comment by jmccl** [comment]
I'd tried mkd_set_flag_num and that wouldn't link either. I do see it's in the code though in "pgm_options.c". However 'nm' shows mkd_set_flag_num isn't in the library and there's no section for pgm_options.o either. If I changed the 'add_library' section of CMakeLists.txt to include pgm_options.c (and gethopt.c because why not and I don't know what I'm doing) then it produces a library that I can link against. (I didn't look at the libtools stuff, other than to note that the same problem appears to be happening there.)

**Comment by Orc** [comment]
Oh, that's a good catch.  I was thinking that it was because the cmakefile was out of date, but it's not.  I added all of the flagging functions into pgm_options, which, of course, means that they won't go into the library at all.   Um, whoops, my bad.  All die, oh the embarrassment!

Let me move those functions out of pgm_options and into the library.  I'll push it to sccs momentarily.

**Comment by jmccl** [comment]
Cool, thanks!

**Comment by jmccl** [comment]
Changes work for me. Thanks for looking at this so quickly.

**Comment by Orc** [comment]
Thank you for bringing it to my attention.  v3 is different enough so that I need to have other eyes building the code to verify things.
