### ISSUE TITLE
Can we get a new release?

### ISSUE THREAD

**Issue by tsdgeos** [Orc/discount#227]
The 2.2.6 release has memory management issues with https://bugs.kde.org/attachment.cgi?id=131134

==12724== Invalid write of size 1
==12724==    at 0x12D8F144: mkd_anchor_format (mkdio.c:258)
==12724==    by 0x12D8F239: mkd_string_to_anchor (mkdio.c:291)
==12724==    by 0x12D94570: Qanchor (generate.c:188)
==12724==    by 0x12D97DC7: printheader (generate.c:1519)
==12724==    by 0x12D98D7F: display (generate.c:1915)
==12724==    by 0x12D989A5: htmlify_paragraphs (generate.c:1775)
==12724==    by 0x12D98A22: htmlify (generate.c:1821)
==12724==    by 0x12D98DB7: display (generate.c:1923)
==12724==    by 0x12D989A5: htmlify_paragraphs (generate.c:1775)
==12724==    by 0x12D98A22: htmlify (generate.c:1821)
==12724==    by 0x12D98FD9: mkd_document (generate.c:1974)
==12724==    by 0x12D84DAA: ??? (in /usr/lib/qt/plugins/okular/generators/okularGenerator_md.so)
==12724==  Address 0xb784738 is 0 bytes after a block of size 152 alloc'd
==12724==    at 0x483A77F: malloc (vg_replace_malloc.c:307)
==12724==    by 0x12D8EF4A: mkd_anchor_format (mkdio.c:237)
==12724==    by 0x12D8F239: mkd_string_to_anchor (mkdio.c:291)
==12724==    by 0x12D94570: Qanchor (generate.c:188)
==12724==    by 0x12D97DC7: printheader (generate.c:1519)
==12724==    by 0x12D98D7F: display (generate.c:1915)
==12724==    by 0x12D989A5: htmlify_paragraphs (generate.c:1775)
==12724==    by 0x12D98A22: htmlify (generate.c:1821)
==12724==    by 0x12D98DB7: display (generate.c:1923)
==12724==    by 0x12D989A5: htmlify_paragraphs (generate.c:1775)
==12724==    by 0x12D98A22: htmlify (generate.c:1821)
==12724==    by 0x12D98FD9: mkd_document (generate.c:1974)

Which are not present anymore if compiling from the main branch.

Could we get a new release with this fixes?

**Comment by Orc** [comment]
What tool are you using to track down the allocation glitch?    My plan was to finish up the 3.0 release as a follow-on to 2.2.6, but a memory allocation bug requires a 2.2.7 release to fix first.

**Comment by tsdgeos** [comment]
the log is from valgrind.

valgrind markdown -f idanchor,fencedcode,githubtags,autolink,toc  -o /dev/null ~/bla.md 

where bla.md is https://bugs.kde.org/attachment.cgi?id=131134

gives me 

==17197== Memcheck, a memory error detector
==17197== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==17197== Using Valgrind-3.16.1 and LibVEX; rerun with -h for copyright info
==17197== Command: ./markdown -f idanchor,fencedcode,githubtags,autolink,toc -o /dev/null /home/tsdgeos/bla.md
==17197== 
==17197== Invalid write of size 1
==17197==    at 0x484C144: mkd_anchor_format (mkdio.c:258)
==17197==    by 0x484C239: mkd_string_to_anchor (mkdio.c:291)
==17197==    by 0x4851570: Qanchor (generate.c:188)
==17197==    by 0x4854DC7: printheader (generate.c:1519)
==17197==    by 0x4855D7F: display (generate.c:1915)
==17197==    by 0x48559A5: htmlify_paragraphs (generate.c:1775)
==17197==    by 0x4855A22: htmlify (generate.c:1821)
==17197==    by 0x4855DB7: display (generate.c:1923)
==17197==    by 0x48559A5: htmlify_paragraphs (generate.c:1775)
==17197==    by 0x4855A22: htmlify (generate.c:1821)
==17197==    by 0x4855FD9: mkd_document (generate.c:1974)
==17197==    by 0x484BDFA: mkd_generatehtml (mkdio.c:193)
==17197==  Address 0x4a9bb38 is 0 bytes after a block of size 152 alloc'd
==17197==    at 0x483A77F: malloc (vg_replace_malloc.c:307)
==17197==    by 0x484BF4A: mkd_anchor_format (mkdio.c:237)
==17197==    by 0x484C239: mkd_string_to_anchor (mkdio.c:291)
==17197==    by 0x4851570: Qanchor (generate.c:188)
==17197==    by 0x4854DC7: printheader (generate.c:1519)
==17197==    by 0x4855D7F: display (generate.c:1915)
==17197==    by 0x48559A5: htmlify_paragraphs (generate.c:1775)
==17197==    by 0x4855A22: htmlify (generate.c:1821)
==17197==    by 0x4855DB7: display (generate.c:1923)
==17197==    by 0x48559A5: htmlify_paragraphs (generate.c:1775)
==17197==    by 0x4855A22: htmlify (generate.c:1821)
==17197==    by 0x4855FD9: mkd_document (generate.c:1974)
==17197== 
==17197== Invalid write of size 1
==17197==    at 0x484C185: mkd_anchor_format (mkdio.c:265)
==17197==    by 0x484C239: mkd_string_to_anchor (mkdio.c:291)
==17197==    by 0x4851570: Qanchor (generate.c:188)
==17197==    by 0x4854DC7: printheader (generate.c:1519)
==17197==    by 0x4855D7F: display (generate.c:1915)
==17197==    by 0x48559A5: htmlify_paragraphs (generate.c:1775)
==17197==    by 0x4855A22: htmlify (generate.c:1821)
==17197==    by 0x4855DB7: display (generate.c:1923)
==17197==    by 0x48559A5: htmlify_paragraphs (generate.c:1775)
==17197==    by 0x4855A22: htmlify (generate.c:1821)
==17197==    by 0x4855FD9: mkd_document (generate.c:1974)
==17197==    by 0x484BDFA: mkd_generatehtml (mkdio.c:193)
==17197==  Address 0x4a9bb39 is 1 bytes after a block of size 152 alloc'd
==17197==    at 0x483A77F: malloc (vg_replace_malloc.c:307)
==17197==    by 0x484BF4A: mkd_anchor_format (mkdio.c:237)
==17197==    by 0x484C239: mkd_string_to_anchor (mkdio.c:291)
==17197==    by 0x4851570: Qanchor (generate.c:188)
==17197==    by 0x4854DC7: printheader (generate.c:1519)
==17197==    by 0x4855D7F: display (generate.c:1915)
==17197==    by 0x48559A5: htmlify_paragraphs (generate.c:1775)
==17197==    by 0x4855A22: htmlify (generate.c:1821)
==17197==    by 0x4855DB7: display (generate.c:1923)
==17197==    by 0x48559A5: htmlify_paragraphs (generate.c:1775)
==17197==    by 0x4855A22: htmlify (generate.c:1821)
==17197==    by 0x4855FD9: mkd_document (generate.c:1974)
==17197== 
==17197== Invalid read of size 1
==17197==    at 0x484C291: mkd_string_to_anchor (mkdio.c:298)
==17197==    by 0x4851570: Qanchor (generate.c:188)
==17197==    by 0x4854DC7: printheader (generate.c:1519)
==17197==    by 0x4855D7F: display (generate.c:1915)
==17197==    by 0x48559A5: htmlify_paragraphs (generate.c:1775)
==17197==    by 0x4855A22: htmlify (generate.c:1821)
==17197==    by 0x4855DB7: display (generate.c:1923)
==17197==    by 0x48559A5: htmlify_paragraphs (generate.c:1775)
==17197==    by 0x4855A22: htmlify (generate.c:1821)
==17197==    by 0x4855FD9: mkd_document (generate.c:1974)
==17197==    by 0x484BDFA: mkd_generatehtml (mkdio.c:193)
==17197==    by 0x10B188: main (main.c:330)
==17197==  Address 0x4a9bb38 is 0 bytes after a block of size 152 alloc'd
==17197==    at 0x483A77F: malloc (vg_replace_malloc.c:307)
==17197==    by 0x484BF4A: mkd_anchor_format (mkdio.c:237)
==17197==    by 0x484C239: mkd_string_to_anchor (mkdio.c:291)
==17197==    by 0x4851570: Qanchor (generate.c:188)
==17197==    by 0x4854DC7: printheader (generate.c:1519)
==17197==    by 0x4855D7F: display (generate.c:1915)
==17197==    by 0x48559A5: htmlify_paragraphs (generate.c:1775)
==17197==    by 0x4855A22: htmlify (generate.c:1821)
==17197==    by 0x4855DB7: display (generate.c:1923)
==17197==    by 0x48559A5: htmlify_paragraphs (generate.c:1775)
==17197==    by 0x4855A22: htmlify (generate.c:1821)
==17197==    by 0x4855FD9: mkd_document (generate.c:1974)
==17197== 
==17197== Invalid read of size 1
==17197==    at 0x484C26B: mkd_string_to_anchor (mkdio.c:299)
==17197==    by 0x4851570: Qanchor (generate.c:188)
==17197==    by 0x4854DC7: printheader (generate.c:1519)
==17197==    by 0x4855D7F: display (generate.c:1915)
==17197==    by 0x48559A5: htmlify_paragraphs (generate.c:1775)
==17197==    by 0x4855A22: htmlify (generate.c:1821)
==17197==    by 0x4855DB7: display (generate.c:1923)
==17197==    by 0x48559A5: htmlify_paragraphs (generate.c:1775)
==17197==    by 0x4855A22: htmlify (generate.c:1821)
==17197==    by 0x4855FD9: mkd_document (generate.c:1974)
==17197==    by 0x484BDFA: mkd_generatehtml (mkdio.c:193)
==17197==    by 0x10B188: main (main.c:330)
==17197==  Address 0x4a9bb38 is 0 bytes after a block of size 152 alloc'd
==17197==    at 0x483A77F: malloc (vg_replace_malloc.c:307)
==17197==    by 0x484BF4A: mkd_anchor_format (mkdio.c:237)
==17197==    by 0x484C239: mkd_string_to_anchor (mkdio.c:291)
==17197==    by 0x4851570: Qanchor (generate.c:188)
==17197==    by 0x4854DC7: printheader (generate.c:1519)
==17197==    by 0x4855D7F: display (generate.c:1915)
==17197==    by 0x48559A5: htmlify_paragraphs (generate.c:1775)
==17197==    by 0x4855A22: htmlify (generate.c:1821)
==17197==    by 0x4855DB7: display (generate.c:1923)
==17197==    by 0x48559A5: htmlify_paragraphs (generate.c:1775)
==17197==    by 0x4855A22: htmlify (generate.c:1821)
==17197==    by 0x4855FD9: mkd_document (generate.c:1974)
==17197== 
==17197== 
==17197== HEAP SUMMARY:
==17197==     in use at exit: 0 bytes in 0 blocks
==17197==   total heap usage: 693 allocs, 693 frees, 435,355 bytes allocated
==17197== 
==17197== All heap blocks were freed -- no leaks are possible
==17197== 
==17197== For lists of detected and suppressed errors, rerun with: -s
==17197== ERROR SUMMARY: 15 errors from 4 contexts (suppressed: 0 from 0)


while main is clean.

**Comment by Orc** [comment]
Aaaiiiee, valgrind.   Normally I do my development on a mac, but I've never had luck hand-building valgrind there.

(Not a showstopper for fixing, I'm just whining that setting up a scratch machine will be a pain :-)

**Comment by Orc** [comment]
How did you configure discount, and what platform was this bug detected on?

**Comment by Orc** [comment]
Nevermind, found it.  It was an ancient stupid bug!   I was trying to precompute the amount of space when generating a label and I forgot to allocate space for the initial marker and the trailing null.

v2.2.7 will be materializing soon, as soon as I can work out how to coax git into making a bugfix branch off v2.2.6  (git is a nice sccs, but the documentation is erratic.)

**Comment by Orc** [comment]
Okay, I've made a v2maint branch, patched that branch, and tagged it as v2.2.7.    Can you try it out and see?   I've valgrinded it on a scratch raspberry pi, and the patched version passes through valgrind without complaint and still passes my test suite (which it SHOULD, because the only differences in the patch are the version#, the added 2 bytes of space allocated in the label formatter, and a tweak to tools/branch that treats v2maint as the mainline.

**Comment by tsdgeos** [comment]
Works great thanks :)

**Comment by Orc** [comment]
Let me give it a couple of days to be sure, and then I'll officially publish the release on my home page (and close this bug)

**Comment by mloskot** [comment]
Has this been confirmed as fixed in 2.2.7? Does this issue qualify to close then?

**Comment by tsdgeos** [comment]
closing it, yes
