### ISSUE TITLE
libmarkdown shared library doesn't honor system LDFLAGS

### ISSUE THREAD

**Issue by antonio-rojas** [Orc/discount#228]
The executables are built with the LDFLAGS from the environment, but the libmarkdown.so shared library does not honor them.

**Comment by Orc** [comment]
Can you elaborate on the problem, because I'm not sure what you mean?

**Comment by antonio-rojas** [comment]
The LINK macro used when building the executables from
https://github.com/Orc/discount/blob/main/Makefile.in#L11
uses the LDFLAGS from the environment..

But the librarian.sh script used to build the libmarkdown library ignores the system LDFLAGS, so they are not applied when building the shared library.
