### ISSUE TITLE
Poorly specified args to tr in configure.inc

### ISSUE THREAD

**Issue by pythontech** [Orc/discount#233]
Hi there,
A little hiccup when building for (an old) Solaris - I got a config.f with invalid lines such as
```C
#define HAVE_SYS/STAT_H 1
```

This is because AC_CHECK_HEADERS in configure.inc invokes tr thus:
```sh
tr './' '_'
```
which would be better as
```sh
tr './' '__'
```

The POSIX manual for tr says:
"When the array specified by string2 is shorter that the one specified by string1, the results are unspecified."

**Comment by Orc** [comment]
And fixed!
