### ISSUE TITLE
configure.inc assumes tr handles character ranges

### ISSUE THREAD

**Issue by pythontech** [Orc/discount#235]
AC_CHECK_ATTRIBUTE pipes the attribute name through
```sh
tr 'a-z' 'A-Z'
```
but this fails if the system's tr does not support character ranges.

It should use $AC_UPPERCASE as defined and used elsewhere in the file.

**Comment by Orc** [comment]
I'm curious;  which platform are you using that catches all of these?

**Comment by pythontech** [comment]
It's Solaris 10, but a lot of the build tools have not been updated for many years (sysadm/management avoiding the cost of recommissioning everything).  I'm jumping through hoops to avoid having to use gcc 2.8.1 =:-()

**Comment by Orc** [comment]
Aaand fixed, I hope.
