### ISSUE TITLE
Reference-style links with angle brackets do not work

### ISSUE THREAD

**Issue by lschierer** [Orc/discount#240]
Per https://daringfireball.net/projects/markdown/syntax#link 
```
The link URL may, optionally, be surrounded by angle brackets:

[id]: <http://example.com/>  "Optional Title Here"
```

however in practice when I try to use angle brackets, I end up with a link that has no target.  That is, it shows on the page as a link, but you cannot click it, and when you view page source, the \<a\> tag has no href attribute.  removing the angle brackets from the link definition and regenerating the html page resolves the issue. 

I'm using discount 2.2.6-1 from ubuntu focal, with libtext-markdown-discount-perl 0.12-1, via ikiwiki 3.20200202.3-1, all installed from ubuntu's packages.

**Comment by Orc** [comment]
Hmm.   What does the generated html look like?   (It *is* broken;  I get unpleasantly funky results testing on the v3 development branch, but I'd love to see your output so I have some more reference failures when debugging this.

**Comment by lschierer** [comment]
```
There seems to be a [transcript available][BoST]
some other text 
some more text

[BoST]: <http://www.link.com/site> 

```
generated 

```
There seems to be a <a>transcriptavailable</a>
some other text 
some more text
```

and 

```
There is a fascinating article on [topic][20210126-1] and the personality traits and skills that go along with ....

[20210126-1]: <https://www.news.site.com/article> "title of article"
```

generates

```
There is a fascinating article on <a title="title of article">topic</a> and the
 personality traits and skills that go along with ....
```

**Comment by Orc** [comment]
It took a while, but I shoved a (tiny!) patch into sccs that trims <> from linky urls.   Can you try it out and see how it works for you?
