### ISSUE TITLE
attempting to link to a url that contains parenthesis acts oddly

### ISSUE THREAD

**Issue by lschierer** [Orc/discount#241]
attempting to link to https://en.wikipedia.org/wiki/Samodiva_(folklore) with a link such as 
```
"[Samodiva (folklore)](https://en.wikipedia.org/wiki/Samodiva_(folklore))"
```
produces a link to https://en.wikipedia.org/wiki/Samodiva_(folklore (note the missing closing paren).  
```
"[Samodiva (folklore)](https://en.wikipedia.org/wiki/Samodiva_(folklore\))"
```
works.

I would understand if I had to escape both opening and closing paren, or if I had to escape neither.  Having to escape only the closing one seems counter-intuitive. 

I'm using discount 2.2.6-1 from ubuntu focal, with libtext-markdown-discount-perl 0.12-1, via ikiwiki 3.20200202.3-1, all installed from ubuntu's packages.

**Comment by Orc** [comment]
That, sadly, is how it's supposed to work -- the reference implementation (<https://daringfireball.net/projects/markdown/dingus>) also clips at the first closing paren.   Alas, you're gonna have to escape the closing paren in the url :-(

**Comment by lschierer** [comment]
Well far be it for me to argue against interoperability.  Is there a good way to report bugs upstream (for lack of a better word)?

**Comment by Orc** [comment]
You can talk to [John Gruber @ daringfireball[(https://daringfireball.net/contact/) about it, but be forewarned that Markdown is a _very_ stable standard and afaik has not been modified in a decade.

**Comment by binki** [comment]
@lschierer

> Well far be it for me to argue against interoperability. Is there a good way to report bugs upstream (for lack of a better word)?

[CommonMark](https://commonmark.org/) is, IMO, the future of Markdown. It tries to provide a well-specified MarkDown-like language which considers many of the common extensions (e.g., things from GFM like code fences) while fixing some idiosyncrasies in Markdown itself. It has been adopted by StackOverflow. It supports the syntax you want, see [its definition of “link destination”](https://spec.commonmark.org/0.29/#link-destination) (and which was already specified/intentioned in the [earliest version](https://spec.commonmark.org/0.5/#link-destination)). You can test this in [its dingus](https://spec.commonmark.org/dingus/).

**Comment by Orc** [comment]
(fyi to anyone reading; discount is a Markdown implementation, not a stackoverflowmark or multimarkdown implementation, and I try to maintain compatibility with Markdown instead of those other much more volatile standards.)

**Comment by lschierer** [comment]
I depend on a couple of the extensions that discount *does* support, such as footnotes, that it looks like would not be supported by switching.  This bug is not nearly annoying enough to give up the benefits of all the things that *do* work well with discount.

**Comment by binki** [comment]
Certainly. But if you want to report something upstream or fix/update the Markdown spec, you’re probably looking for something other than Markdown ;-).
