### ISSUE TITLE
What about to add `pikchr` support?

### ISSUE THREAD

**Issue by podsvirov** [Orc/discount#242]
[Pikchr](https://pikchr.org/) (pronounced "picture") is a [PIC](https://en.wikipedia.org/wiki/Pic_language)-like markup language for diagrams in technical documentation.

Embedding simple graphics in simple documents seems like a natural solution.

Is there any interest in this functionality?

**Comment by Orc** [comment]
I've got a code block callback function (`mkd_e_code_format(MMIOT *document, mkd_e_callback)`) that lets you do that. 

Look at the function `external_code()` in `main.c`for an example of how it works.
