### ISSUE TITLE
--with-dl=both has no effect

### ISSUE THREAD

**Issue by Zorgodon** [Orc/discount#243]
I would like to use the markdown extra (:) style definition lists with `mkd2html`, since `markdown`  appears to have no css command line option. I've run
```
./configure.sh --prefix=/usr --with-dl=both
sudo make install.everything
```
but I still get a literal `:` printed in mkd2html and markdown when using extra-style syntax.
Discount syntax (=) always works, even if compiled with `--with-dl=extra`
What am I doing wrong?
[test.md](https://github.com/Orc/discount/files/6604432/test.md)

**Comment by Orc** [comment]
I've switched 99% of the options in discount to being set by runtime flags, so you need to set the flag `MKD_DLEXTRA` to enable it (programmatically by `mkd_set_flag_num(MMIOT*, MKD_DLEXTRA)`, `markdown -fdlextra` from the command line.)

Yes, this is woefully undocumented.  I am, as they say, "working on it" `:-(`

**Comment by Zorgodon** [comment]
In that case, is there any way to specify a css file to the `markdown` command, or would I have to `sed` it in manually? I could only find the option for `mkd2html`.

**Comment by Orc** [comment]
Building a wrapper script to insert styles is probably your best bet, because css really prefers to sit in a document header or be imbedded in a html element, neither of which is within the scope of the markdown format.
