### ISSUE TITLE
Support for <div>/block tag "markdown" attribute 

### ISSUE THREAD

**Issue by rc4** [Orc/discount#244]
Hello,

Firstly, thanks for the wonderful library & tools! I know that the markdown spec says that markdown processing is disabled inside block-level tags like `<div>`s, but this can make it difficult to style markdown-generated HTML pages. Something (non-standard) I've seen several other libraries implement is a "markdown" attribute, like this: `<div markdown="1">`; the attribute is removed from the resultant HTML, but signals to the parser that markdown processing should occur inside of that element. Here's an example of it in the Python Markdown library: https://python-markdown.github.io/extensions/md_in_html/. 

I would imagine that this wouldn't run afoul of any tests/compliance checks if enabled by default, since the attribute has to be consciously added by the author. Would it be possible to have this feature added to discount? I'd be happy to try and take a stab at it myself, but I've never submitted a patch to an open-source project before, so I'm not totally sure of the etiquette surrounding that (or how to best write the patch/structure the code to your standards).

Thanks again!

**Comment by rc4** [comment]
Whoops. Guess I didn't search the previous issues very well. :)

**Comment by rc4** [comment]
Was #66 ever merged in? It doesn't seem to have been. Are there plans to merge it or any issues preventing it from being merged?

**Comment by Orc** [comment]
I did put something like that in;  I mentioned it as part of #66, but if you're going to do it inside a div
the best way is to do a tagged blockquote -- `>%id:id%` will give you a div instead of a blockquote,
with the contents properly formatted.
