### ISSUE TITLE
configure.sh exceeds Plan 9 posix sh (pdksh) break level limit

### ISSUE THREAD

**Issue by joshix** [Orc/discount#249]
In `discount/configure.inc:489` -> `configure.sh` the script shorts an inner inner loop with `break 3`. Under Plan 9 posix environment, this gives:

`./configure.sh: ./configure.inc[1832]: break: can only break 2 level(s)`

Plan9 APE sh (pdksh) limits break to 2 levels. Configure.sh ends up in Broken state but does generate the Makefile.

**Comment by Orc** [comment]
Ugh.   Not so much for 'break 3' not working, but for me putting it in instead of just restoring IFS and returning immediately from the offending function!

That was easy to patch, and I've pushed a patch for it up to the github mirror.  Thanks for reporting it!
