### ISSUE TITLE
Allow fenced code blocks without a preceding blank line

### ISSUE THREAD

**Issue by digital-carver** [Orc/discount#250]
`discount` seems to expect an empty line before a Github-flavored fenced code block (`-ffencedcode`), and seems not to recognize such code blocks when such an empty line is not present. 

See for eg. https://github.com/JuliaData/Tables.jl/blob/main/docs/src/index.md - the second code block (under "Using the Interface") is rendered correctly by Github, but when I run `markdown -o output.html -ffencedcode index.md`, the resulting file does not have a `<code>` block corresponding to that fenced block; the contents get rendered as just another part of the preceding paragraph. 

As a reference, the [Github Flavored Markdown Spec]() also explicitly states: 

> A fenced code block may interrupt a paragraph, and does not require a blank line either before or after.

(Tested the above behaviour both with discount 2.2.7 and the latest `main` branch code here.)

**Comment by Orc** [comment]
What does the generated-by-github markup look like?

**Comment by digital-carver** [comment]
I'm not sure I understand - the Github-generated page is what I linked to. Could you clarify what you mean? 

In the course of trying to get a minimal example of this, I found that the issue reported only seems to happen when there is a line starting with a `#` within the code block: the parser seems to get that confused with the usual meaning of `#` as `<h1>` indicator, and that throws the whole fenced code block into disarray. 


Here's three small files and their outputs (separated by "------" lines):

`````

~/t/discount-main$ cat file1.md && echo '------' && ./markdown -ffencedcode file1.md                                         

At a high level, Tables.jl provides two powerful APIs:
```julia
# access data of input table `x` row-by-row
# Tables.rows must return a row iterator
rows = Tables.rows(x)
```
------
<p>At a high level, Tables.jl provides two powerful APIs:
```julia</p>

<h1>access data of input table <code>x</code> row-by-row</h1>

<h1>Tables.rows must return a row iterator</h1>

<p>rows = Tables.rows(x)
```</p>


~/t/discount-main$ cat file2.md && echo '------' && ./markdown -ffencedcode file2.md                                         

At a high level, Tables.jl provides two powerful APIs:
```julia
 access data of input table `x` row-by-row
# Tables.rows must return a row iterator
rows = Tables.rows(x)
```
------
<p>At a high level, Tables.jl provides two powerful APIs:
<code>``julia
 access data of input table</code>x` row-by-row</p>

<h1>Tables.rows must return a row iterator</h1>

<p>rows = Tables.rows(x)
```</p>

~/t/discount-main$ cat file3.md && echo '------' && ./markdown -ffencedcode file3.md                                         

At a high level, Tables.jl provides two powerful APIs:
```julia
 access data of input table `x` row-by-row
 Tables.rows must return a row iterator
rows = Tables.rows(x)
```
------
<p>At a high level, Tables.jl provides two powerful APIs:
<code>julia
 access data of input table `x` row-by-row
 Tables.rows must return a row iterator
rows = Tables.rows(x)
</code></p>

`````

The first one shows the original issue: the code block isn't recognized, and the output is normal HTML text of paragraphs, headers, etc.. 

The second one is a weird case: I removed the `#` from the first line. Since the second line still has it, the problem still occurs, but this time, since there's a ``` `x` ``` in the first line, the ```` ```julia ```` seems to be interpreted as a backtick, followed by code starting with two backticks, and ending with the backtick which is actually the start of ``` `x` ```. Hence, that part alone is marked as code. 

The third one is nearly the expected behaviour - since there is no `#`-beginning lines in the code. However, it still has a problem, if I understand correctly - I believe the ```` ```julia ```` annotation is supposed to become the class of the code block: "you can put a word at the end of the opening backtick line and have the block given that class" [source](https://www.pell.portland.or.us/~orc/Code/markdown/). Here, instead, the `julia` seems to have become part of the code. 

Sorry, that's an overwhelming amount of information; I wanted to make sure to report the issues as and when I see them, so the information isn't lost. Hope the output above makes things clear, if not please let me know what I can do to change that.

**Comment by Orc** [comment]
Thank you!;  I was wondering if it broke the embedded ``` code out into a separate para or not.  It should (???) be fixable without any compatibility breakage.

**Comment by Orc** [comment]
Okay, take a look at the new branch `fencerepair`;   that changes the behavior of fenced code blocks to be more along the lines of what you're looking for

**Comment by digital-carver** [comment]
That works great for the examples in my previous comment, detecting the code blocks and setting them to the right class too. 

However, when I try it on an actual file, the results are pretty garbled. Here's a small section of a file (the original full file is from a project called Tables.jl. [Github-rendered link to full file](https://github.com/JuliaData/Tables.jl/blob/138c5beab96df972c80e1e9ea6239429cc4ddcb0/docs/src/index.md) | [raw link](https://github.com/JuliaData/Tables.jl/raw/138c5beab96df972c80e1e9ea6239429cc4ddcb0/docs/src/index.md)): 

````
### `Tables.columns` usage

Ok, now let's take a look at a case utlizing [`Tables.columns`](@ref).
The following code is taken from the [DataFrames.jl](https://github.com/JuliaData/DataFrames.jl/blob/master/src/other/tables.jl)
Tables.jl implementation:
```julia
getvector(x::AbstractVector) = x
getvector(x) = collect(x)

# note that copycols is ignored in this definition (Tables.CopiedColumns implies copies have already been made)
fromcolumns(x::Tables.CopiedColumns, names; copycols::Bool=true) =
    DataFrame(AbstractVector[getvector(Tables.getcolumn(x, nm) for nm in names],
              Index(names),
              copycols=false)
[...]
```

So here we have a generic `DataFrame` constructor that takes a single, untyped argument,
calls [`Tables.columns`](@ref) on it, then [`Tables.columnnames`](@ref) to get the column names.
It then passes the [`Tables.AbstractColumns`](@ref)-compatible object to an internal function `fromcolumns`,
which dispatches on a special kind of `Tables.AbstractColumns` object called a [`Tables.CopiedColumns`](@ref),
````

Github has no problems rendering this (except for slight difference in newline behaviour due to Github flavored markdown): 

---

### `Tables.columns` usage

Ok, now let's take a look at a case utlizing [`Tables.columns`](@ref).
The following code is taken from the [DataFrames.jl](https://github.com/JuliaData/DataFrames.jl/blob/master/src/other/tables.jl)
Tables.jl implementation:
```julia
getvector(x::AbstractVector) = x
getvector(x) = collect(x)

# note that copycols is ignored in this definition (Tables.CopiedColumns implies copies have already been made)
fromcolumns(x::Tables.CopiedColumns, names; copycols::Bool=true) =
    DataFrame(AbstractVector[getvector(Tables.getcolumn(x, nm) for nm in names],
              Index(names),
              copycols=false)
[...]
```

So here we have a generic `DataFrame` constructor that takes a single, untyped argument,
calls [`Tables.columns`](@ref) on it, then [`Tables.columnnames`](@ref) to get the column names.
It then passes the [`Tables.AbstractColumns`](@ref)-compatible object to an internal function `fromcolumns`,
which dispatches on a special kind of `Tables.AbstractColumns` object called a [`Tables.CopiedColumns`](@ref),

----

whereas the `discount`-rendered output has code blocks at the wrong places, and has entire lines vanish because their content has been set (wrongly) as `class`values instead. [Here's a JSFiddle containing discount's output and its rendering](https://jsfiddle.net/qxrm3apc/2/). 

The `Ok` under the first heading in the markdown seems to be for some reason treated as if it was a triple-backtick, starting a code block and setting the rest of that line as the `class` value. That messes with the parsing of a lot of what follows too. And in the full file linked above, this happens multiple times in multiple places, so it doesn't seem something specific to that line either.

**Comment by Orc** [comment]
The line classifier was misdetecting fences;  I just pushed an update for it that appears to properly detect the code blocks in your document.

**Comment by digital-carver** [comment]
Thank you for the quick update. 

One remaining issue that I found by running it on the [full file](https://github.com/JuliaData/Tables.jl/raw/138c5beab96df972c80e1e9ea6239429cc4ddcb0/docs/src/index.md) is with this section: 

````
This is pretty straightforward usage: it calls [`Tables.rows`](@ref) on the input table source,
and since we need the schema to setup the database table, we query it via [`Tables.schema`](@ref).
We then iterate the rows in our table via `for row in rows`, and use the convenient
[`Tables.eachcolumn`](@ref) to efficiently apply a function to each value in the row. Note that
we didn't call [`Tables.columnnames`](@ref) or [`Tables.getcolumn`](@ref) at all, since they're utilized
by [`Tables.eachcolumn`](@ref) itself. [`Tables.eachcolumn`](@ref) is optimized to provide type-stable, and even
constant-propagation of column index, name, and type in some cases to allow for efficient
consumption of row values.

One wrinkle to consider is the "unknown schema" case; i.e. what if our [`Tables.schema`](@ref)
call had returned `nothing` (this can be the case for exotic table sources like lazily mapped
transformations over rows in a table):
```julia
function load!(sch::Nothing, rows, db::SQLite.DB, tablename)
    ...
    return name
end
```

The strategy taken here is to start iterating the input source, and using the first row

````

The problem, as far as I can tell, occurs when there's a line starting with a square bracket `[` (the 4th line above), and then a fenced code block somewhere after that.  In such a case, the bracket `[` seems to be treated like a triple-backtick, the rest of that paragraph as the code `class` (hence doesn't appear as content in the document), and this throws off the parsing of the rest of the document too.

**Comment by Orc** [comment]
Ugh.  It was worse than that; my fenced code detection was too clever by half and I only partially unclevered it with the patch.

I've pushed another update over to the mirror here which _does_ actually correctly (ie: not as a fenced code marker) process `[\`label\`]` starting at the beginning of the line.

**Comment by Orc** [comment]
After running with the fencerepair code for 2 months now without it blowing anything up I've merged that branch into the mainline and _I think_ that it should make it work better for you.   Please reopen this request if it blows up in mysterious ways!
