### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by greg-hellings** [Orc/discount#253]
Please tag a new release. There are several small build fixes that I have to patch and maintain in Fedora in order to get it to build. These are already fixed in this repo, and it would be nice to be able to drop the patches in the packaging.

**Comment by Orc** [comment]
Are you working with the last 2.x release or the new(ish) 3.x branch?

**Comment by greg-hellings** [comment]
I'm packaging the latest release, so that's still 2.x

**Comment by Orc** [comment]
Which patches do you need?  The v2 release (2.2.7) is sccs tagged at v2maint/HEAD and published on my website, so if you're pulling main/HEAD from github you're actually getting a version 3 beta.

**Comment by greg-hellings** [comment]
[This](https://github.com/Orc/discount/commit/c00ad392bf96d723f4ae01edebb3328290d11a5c) is the change that I needed to patch in 2.2.7 in order to get parallel builds to work properly.

**Comment by Orc** [comment]
Thank you!

I've cherry-picked that patch into the v2maint branch and tagged it with v2.2.7b;   I'll be publishing it on the official site this afternoon, but if you want to pull from github the head of the v2maint branch should be correctly tagged for you.

-david parsons
