### ISSUE TITLE
space2nl.c missing from github master (1473d6b678fad3bf3145ac6454f76c4146c4cb6d)

### ISSUE THREAD

**Issue by balducci** [Orc/discount#254]
hi
attempting to build master (1473d6b678fad3bf3145ac6454f76c4146c4cb6d) cloned from github fails for me with:
```
make[1]: *** No rule to make target 'tools/space2nl.c', needed by 'space2nl.o'.  Stop.
```
and, actually, I cannot find ``space2nl.c`` in the cloned tree

Building on linux w/gcc and configuring with:

```
--shared
--pkg-config
```

thanks
-gabriele

**Comment by Orc** [comment]
Github _finally_ didn't server error when I tried to push things over, so you should be set now?
