### ISSUE TITLE
`isprint`/`isspace` undefined behavior

### ISSUE THREAD

**Issue by tntxtnt** [Orc/discount#255]
On line 123 in `mkdio.c`: https://github.com/Orc/discount/blob/main/mkdio.c#L123

Call `mkd_string`, `mkd_compile`, `mkd_document` don't crash, but  when you call `mkd_cleanup` with MSVC build (VS2022 17.2.1), program crashes. Debugger points to line 123 in `mkdio.c`. It appears that `isprint(c)`/`isspace(c)` is UB if `c` is not representable as `unsigned char` (and is not equal to EOF)
https://en.cppreference.com/w/c/string/byte/isprint
https://en.cppreference.com/w/c/string/byte/isspace

Possible fix: move `(c & 0x80)` in front of `isprint` and `isspace`
```c
else if ( (c & 0x80) || isprint(c) || isspace(c) )
```

**Comment by Orc** [comment]
Can you give me a piece of example markdown source that provokes this behavior?

**Comment by Orc** [comment]
Yeah, the C++ definition of functions is often subtly different than what C's definitions are.   MSC++ throwing an error is, um, not exactly a well-mannered behavior.

I changed the order of the checks to utf-8 first, then the two function calls afterwards.    That might do the trick (this is a behavior that cannot be reproduced on any of my Unix/Linux/BSD/MacOS machines) for you.   It's in the fencerepair branch for now, but will migrate back to main fairly soon when I collapse fencerepair into it.

**Comment by Orc** [comment]
The fencerepair branch with the utf-8 check moved to before the is... functions is now merged into the baseline, so I'm going to close this issue.   Please reopen it if it doesn't fix things for you.
