### ISSUE TITLE
Update discount / markdown mkd2html DOCTYPE to HTML5

### ISSUE THREAD

**Issue by gnbl** [Orc/discount#257]
https://github.com/Orc/discount/blob/main/mkd2html.c#L198 write `<!doctype html public "-//W3C//DTD HTML 4.0 Transitional //EN">`.

According to https://en.wikipedia.org/wiki/HTML#Transition_of_HTML_Publication_to_WHATWG, it should be `<!DOCTYPE html>` for HTML5.

**Comment by gnbl** [comment]
I compiled it myself:

```
diff --git a/mkd2html.c b/mkd2html.c
index f3ee435..43bd59f 100644
--- a/mkd2html.c
+++ b/mkd2html.c
@@ -195,7 +195,7 @@ char **argv;
     /* print a header */
 
     fprintf(output,
-       "<!doctype html public \"-//W3C//DTD HTML 4.0 Transitional //EN\">\n"
+       "<!doctype html>\n"
        "<html>\n"
        "<head>\n"
        "  <meta name=\"GENERATOR\" content=\"mkd2html %s\">\n", markdown_version);

```
On Ubuntu `$ sudo make install install.samples` installs to `/usr/local/bin/mkd2html` but 

```
$ mkd2html
bash: /usr/bin/mkd2html: No such file or directory
```

Not sure if that's right and where BINDIR in the Makefile comes from.

**Comment by Orc** [comment]
I looked through the html5 reference and I don't think it excludes any of the markup that discount/markdown generates, so it seems like a simple enough revision (though I'm not going to do the lazy markup the WHAT?? documentation says is possible!)

**Comment by gnbl** [comment]
Thanks, the change is in https://github.com/Orc/discount/commit/4cdcac0d9018b344b66ed2f2361bf8b337d66e7b
