### ISSUE TITLE
Markups symbols not working in lib

### ISSUE THREAD

**Issue by vlccek** [Orc/discount#259]
Hi, I'm using discount as a library. I have issues with markdown content in markups (bolt text, italics text). Generation is not working for this content. I am not using any flag. Can you help what i'am doing wrong?

This is the function what i'am using:
```c++
char *MKIOT::genHtml(int flags) {
  mkd_compile(mmiot, &flags);
  char *text;
  mkd_document(mmiot, &text);
  return text;
}
```

`**bold text**` -> \*\*bold text\*\*

**Comment by Orc** [comment]
Which version are you using, and does other markup work with it?

**Comment by vlccek** [comment]
This repo, the latest version from the main branch. I just find out that links do not work too. Heading works as expected.

**Comment by Orc** [comment]
The format of flags has changed in version 3 (I'm working on the documentation rn) and mkd_flag_t is no longer a scalar, but a pointer to a flags blob.   It's _possible_ that this is the bug.

Are you doing anything with the headers for c++?    I'm going to build a little testcase for this, and want to try and duplicate your code to do it.

**Comment by Orc** [comment]
Oh for pete's sake I forgot to update it.  Goddamn.   It doesn't explain why it's not working for you, but I need to update the class to be compatible with the v3 published interface.

**Comment by vlccek** [comment]
Does v3 discount have flag for disabling bold text,links etc? Or this should be case? I've try to use older version and  with that i have no issues. So my only explanation is that i make same mistake with flags. Or did yiu have some others idea?

**Comment by Orc** [comment]
Ugh.  I dropped my reply to this on the floor;  I don't think I've ever had an option to disable text formatting;  are you thinking of the MKD_SAFELINK option that checks for well-known protocols?
