### ISSUE TITLE
Rendering of the <style> tag

### ISSUE THREAD

**Issue by fliiiix** [Orc/discount#265]
```
[❤ l33tname@fedora:~] markdown --version
markdown: discount 2.2.7c
[❤ l33tname@fedora:~] cat foo.md 
Hello *github*
<style type='text/css' media='screen'>
p{margin:5px}
</style>

<h2>foo</h2>
[❤ l33tname@fedora:~] markdown foo.md 
<p>Hello <em>github</em></p>





<h2>foo</h2>
```

Is that a bug or are we holding it wrong? For some reason the `style` tag is filtered. 
I also checked in dingus which does the right thing. 
![image](https://user-images.githubusercontent.com/1682954/201479575-fd9027c0-649d-4be2-8cc3-c7909f5dff3a.png)

This issue was raise in `rdiscount` (https://github.com/davidfstr/rdiscount/issues/149) but unless we are holding it wrong i assume that is a bug here.

**Comment by Orc** [comment]
That's actually as designed.   But you can disable that behavior with -fnostyle (the flag MKD_NOSTYLE if you're using discount as a library)

**Comment by fliiiix** [comment]
Thanks for your fast reply! :tada: :sparkles: 

## bug
Ok i guess I found what the *bug* is because we have a test in rdiscount which worked without setting the `MKD_NOSTYLE` flag.

```
[✖ l33tname@fedora:~] markdown foo.md 
<p>Hello <em>github</em><style type='text/css' media='screen'>p{margin:5px}</style></p>
[❤ l33tname@fedora:~] cat foo.md 
Hello *github*<style type='text/css' media='screen'>p{margin:5px}</style>
```

If the style text is inline it does not get filtered out, which probably should happen since that produces valid html with a style tag.

## Nitpick
If you look into this I also would have a nitpick:
```
[❤ l33tname@fedora:~] cat foo.md 
Hello
<style>
p { margin: 5px; }
</style>
[❤ l33tname@fedora:~] markdown -fnostyle foo.md
<p>Hello</p>

<style>
p { margin: 5px; }
</style>

[❤ l33tname@fedora:~] 
```

See the extra `\n` before and after the `<style>` block.
