### ISSUE TITLE
Call to ldconfig in librarian.sh cannot be disabled

### ISSUE THREAD

**Issue by danielnachun** [Orc/discount#266]
We are currently trying to build `discount` with shared libraries in Homebrew, and have found that the `librarian.sh` script for building the shared library has a hard-coded call to `ldconfig` that cannot be disabled.  This is problematic because calling `ldconfig` normally requires root access to update `ld.so.cache` which is not allowed by Homebrew and other overlay package managers such as a Anaconda, and in some Linux environments root access is also restricted.

At a minimum there should be an option to skip this step that can be passed through `configure.sh`, though it may be worth considering whether `ldconfig` should be invoked in a build script like this at all.  As I understand it, using `ldconfig` to update `ld.so.cache` is normally only done by a host package manager such as `apt` or `yum` after packages have been updated, and overlay package managers such as Homebrew and Anaconda use RPATH instead of `ld.so.cache` to find shared libraries.

Please let me know if any further information is needed to better understand the problem!

**Comment by Orc** [comment]
What OS is the machine running?   It should only call ldconfig when doing an install; do your package managers build & install as someone other than root?

**Comment by danielnachun** [comment]
We do all of our builds for Homebrew inside a Ubuntu 22.04 VM running through GitHub Actions, and they are not run as `root`.   This is by design because Homebrew is an overlay package manager that is only supposed to modify files inside its installation directory (`/home/linuxbrew/.linuxbrew` by default) during the build, and all packages should be buildable from source by end users who may not have root access.

**Comment by Orc** [comment]
Sorry about the delay, but I have just now pushed a patch that adds the `--container` option to configure.sh; if set, ldconfig will not be added into librarian install.
