### ISSUE TITLE
New release soon?

### ISSUE THREAD

**Issue by benkohler** [Orc/discount#268]
In the code & git log I see a few references to 2.2.7c, 3, and 3.0.0a... but no tags to match.  Will a new release be tagged any time soon?

There are a few fixes I'd like to see in our repo but I can package a snapshot for now.

Thanks!

**Comment by Orc** [comment]
I'm not sure what happened to 2.2.7c, but it turns out that 3.0.0a was tagged but never pushed to the github mirror.    Whoops.   I just now did that, and need to look back at the v2maint branch to see what happened with 2.2.7c.

**Comment by Orc** [comment]
The reason why there's been no formal release for a long time is that I've changed the flags from a bitmap to an opaque blob, which means there's a whole bunch of documentation before I can package an official release, and the ongoing plague has made it v e r y h a r d to finish writing said documentation.   Sigh.  It's on my todo list.

**Comment by chenrui333** [comment]
👋 @Orc, it looks like the artifact on the homepage is still using `2.2.7b`
https://www.pell.portland.or.us/~orc/Code/discount/

**Comment by Orc** [comment]
I needed to check if the v2maint branch was correctly up to date, but I've now marked top of v2maint stack as v2.2.7c
