### ISSUE TITLE
Flag for copying img alt text to title.

### ISSUE THREAD

**Issue by justinmeiners** [Orc/discount#269]
Some markdown processors allow you to use the image `alt` text for the `title` as well. In the browser, this provides a hover over tooltip to provide additional info about the image.

**Comment by Orc** [comment]
What does the generated html look like?  just tossing a title={contents-of-[]) into the mess of attributes, or something fancier?

**Comment by justinmeiners** [comment]
@Orc Yes, just adding an attribute is what I hoped for:

`![$alt](image/path.png) => <img alt="$alt" title="$alt" ...>`

It looks like some provide this feature, alongside more configuration options, like the ability to optionally specify both an alt and a title. See: https://dev.to/stephencweiss/markdown-image-titles-and-alt-text-5fi1. I don't care as much about those options, but will make you aware of them.

**Comment by Orc** [comment]
That looks easy enough to implement;  a runtime flag (MKD_ALT_TITLE), plus a if !title title=alt conditional in the code.  Lemme stuff it into my baseline this afternoon;  I'll push a copy here and let you know when it has started to work.

**Comment by justinmeiners** [comment]
Incredible! Thanks for the great tool.

**Comment by Orc** [comment]
Whoops, I forgot to actually commit the changes.   I've shoved them in at top of @main here; the new flag is MKD_ALT_AS_TITLE, and it currently only works with image links.
