### ISSUE TITLE
About the latest release

### ISSUE THREAD

**Issue by chenrui333** [Orc/discount#270]
👋 I saw there are two tags since 2.2.7b, namely, 2.2.7c and 3.0.0a, but the download page still points to 2.2.7b, which one would be considered as the latest release? Thanks!

**Comment by p-linnane** [comment]
@Orc can you please clarify here? Thank you.

**Comment by Orc** [comment]
I've been trying to rewrite the documentation & restructure the web pages for discount v3, and it's eaten up more spoons that I ever thought possible.

But 2.2.7c _should_ have been published, but alas it was not and I put in another bugfix, which moves $$HEAD up to v2.2.7d (published on the official site, pushed here.)

**Comment by leahneukirchen** [comment]
I don't see 2.2.7d on https://github.com/Orc/discount/tags ?

**Comment by Orc** [comment]
Ugh.  Once again I got bit by the idiotic misfeature of git push --all *not including tags*;  fixed, I hope.

**Comment by leahneukirchen** [comment]
Works now, thanks! You need `--follow-tags` yeah...

**Comment by McSinyx** [comment]
FWIW like all other options, you can set this in the configuration file:

[push]
	followTags = true

It is beyond me why this is not the default.
