### ISSUE TITLE
Mishandling of two footnotes one after another

### ISSUE THREAD

**Issue by NunoSempere** [Orc/discount#272]
```
printf "Hello[^1][^2]\n\n[^1]: world\n\n[^2]: from Hamburg" | markdown -f footnotes
```

produces 

```
<p>Hello<a href="">^1</a></p>
```

Contrast with 

```
printf "Hello[^1]\n[^1]: world" | markdown -f footnotes
```

or with 

```
printf "Hello[^1]world[^2]\n[^1]: Guten\n[^2]: tag" | markdown -f footnotes
```

I've tried to look at the extra_linky and linky_linky functions in generate.c, but they went over my head. That said, if you want to give me some pointers, it might be a good first issue for me? Not sure, this code base seems pretty intimidating.

**Comment by Orc** [comment]
M-E footnotes were wedged in as an afterthought, and not implemented nearly as well as they should have been.  The tag handling code in linkylinky is kludgy in the extreme; I do not check that it's a M-E footnote right when I come back from linkylabel, but further down *after* I've checked that it's not a `[]()` link.

The code is bad, so it's not concise, so it even took me a bit to find it.    Try this patch and tell me if it fixes your problem, and if you can find a better way to implement it I will _happily_ take your patch instead.

~~~~
diff --git a/generate.c b/generate.c
index ee6159a..2ffe03f 100644
--- a/generate.c
+++ b/generate.c
@@ -775,26 +775,29 @@ linkylinky(int image, MMIOT *f)
        else {
            int goodlink, implicit_mark = mmiottell(f);
 
-           if ( isspace(peek(f,1)) )
-               pull(f);
-
-           if ( peek(f,1) == '[' ) {
-               pull(f);        /* consume leading '[' */
-               goodlink = linkylabel(f, &key.tag);
+           if ( is_flag_set(&f->flags, MKD_EXTRA_FOOTNOTE)
+                     && !is_flag_set(&f->flags, MKD_STRICT)
+                     && (!image)
+                     && S(name)
+                     && T(name)[0] == '^' ) {
+               extra_footnote = 1;
+               goodlink = 1;
            }
            else {
-               /* new markdown implicit name syntax doesn't
-                * require a second []
-                */
-               mmiotseek(f, implicit_mark);
-               goodlink = !is_flag_set(&f->flags, MKD_1_COMPAT);
-
-               if ( is_flag_set(&f->flags, MKD_EXTRA_FOOTNOTE)
-                         && !is_flag_set(&f->flags, MKD_STRICT)
-                         && (!image)
-                         && S(name)
-                         && T(name)[0] == '^' )
-                   extra_footnote = 1;
+               if ( isspace(peek(f,1)) )
+                   pull(f);
+
+               if ( peek(f,1) == '[' ) {
+                   pull(f);    /* consume leading '[' */
+                   goodlink = linkylabel(f, &key.tag);
+               }
+               else {
+                   /* new markdown implicit name syntax doesn't
+                    * require a second []
+                    */
+                   mmiotseek(f, implicit_mark);
+                   goodlink = !is_flag_set(&f->flags, MKD_1_COMPAT);
+               }
            }
 
            if ( goodlink ) {
diff --git a/tests/extrafootnotes.t b/tests/extrafootnotes.t
index d7a5ed5..8d05913 100644
--- a/tests/extrafootnotes.t
+++ b/tests/extrafootnotes.t
@@ -28,6 +28,20 @@ yes?<a href="#footref:1" rev="footnote">&#8617;</a></li>
 </ol>
 </div>'
 
+try -ffootnote 'footnotes(two adjacent footnotes)' 'Hello[^1][^2]
+
+[^1]: world
+[^2]: from Hamburg' '<p>Hello<sup id="fnref:1"><a href="#fn:1" rel="footnote">1</a></sup><sup id="fnref:2"><a href="#fn:2" rel="footnote">2</a></sup></p>
+<div class="footnotes">
+<hr/>
+<ol>
+<li id="fn:1">
+world<a href="#fnref:1" rev="footnote">&#8617;</a></li>
+<li id="fn:2">
+from Hamburg<a href="#fnref:2" rev="footnote">&#8617;</a></li>
+</ol>
+</div>'
+
 try -fnofootnote 'footnotes (-fnofootnote)' "$FOOTIE" \
 '<p>I haz a footnote<a href="yes?">^1</a></p>'
~~~~

**Comment by Orc** [comment]
> On Aug 17, 2023, at 1:20 AM, Nuño Sempere ***@***.***> wrote:
> 
> 
> I'm having some difficulties applying this patch. I think that Github is mucking tabs and whitespaces, and git apply --whitespace=fix isn't working. Would you do me a favour and upload your patch as a file, e.g., to https://gist.github.com/ <https://gist.github.com/>?
> 


Sure!  Try ***@***.***:ad8f34065b72ffebbd0792b1efbf4f02.git

-david parsons

**Comment by NunoSempere** [comment]
Thanks

>  Try this patch and tell me if it fixes your problem

I've now applied this patch and it does solve my problem.

**Comment by NunoSempere** [comment]
I tried writing a (much more bare-bones) markdown parser this weekend, and ran into a similar issue :) <https://github.com/NunoSempere/nunomark/blob/master/main.go#L413>

**Comment by Orc** [comment]
I don't think that's a mishandling;  it falls into the [][] link code where the contents of the first [] is the description and the second [] is the note label.    Do other implementations do it differently?

**Comment by Orc** [comment]
Ugh, nevermind, I was replying to your first comment from 2023.   Lemme look at the g* parser.

**Comment by Orc** [comment]
It's a nice terse little parser you've written.   Are you grabbing the entire linkylinky first, then picking apart the contents of the two [][]s?   Because you need to break out early if it turns out to be a special footnote link.

**Comment by NunoSempere** [comment]
> It's a nice terse little parser you've written

Thanks!

> Are you grabbing the entire linkylinky first, then picking apart the contents of the two [][]s?   

I'm writing something like a state machine for each markdown feature. Footnotes come after links and images (and I'm not worrying too much about interactions, e.g., `[^caption](https://test.com)` would get parsed as a link). 

Then in the specific footnote state machine, I handle the case of several footnotes together here:  
https://github.com/NunoSempere/nunomark/blob/b0affbc5f9938461798bb4f66e6dd3107d551734/main.go#L437

> Because you need to break out early if it turns out to be a special footnote link.

Not sure quite a special footnote link is refering to.

**Comment by Orc** [comment]
The special footnote link is one that's got the I-am-a-footnote caret in it.
