### ISSUE TITLE
[Feature suggestion] Relaxed parsing for <?theme action?>

### ISSUE THREAD

**Issue by fancsali** [Orc/discount#273]
As far as I could tell, the parser will insist, that there is _no_ spaces between the theme-tag opening/closing `<?`/`?>` and the keywords. So at the moment this would not be understood:

```
`<? theme body ?>`
```

I am proposing to modify the parser to accept white-space there.

**Comment by Orc** [comment]
Sure, if you'd be willing to adhere to the existing licence!
