### ISSUE TITLE
[Feature suggestion] Allow class-blocks with multiple classes

### ISSUE THREAD

**Issue by fancsali** [Orc/discount#274]
It seems to me, this is currently not supported:

```
> %class-one class-two%
>
> Lorem ipsum...

```

I am proposing to allow spaces in the 'class-name' between the `%`-signs, thus allowing multiple classes to be added.

**Comment by Orc** [comment]
Sorry for the delay, but I've made a patch and synced it over here.  Can you test it out and let me know if it works for you?

**Comment by fancsali** [comment]
No worries, had a go and it works; thanks!

Also raised an MR against the Alpine package... ;)
