### ISSUE TITLE
Fence code block issue

### ISSUE THREAD

**Issue by Sebultura** [Orc/discount#286]
Hi, I was told that  this repo is used as a backend for the Okular software for handling Markdown rendering?
If it's the case, here's the thing:
* when we use a fence code block with an empty line just before, then the rendering is good
* when we use a fence code block without an empty line, then it seems to be treated as an inline code..

To reproduce:
(good_rendering.md)
First line

```
Code
fence
```
Last line
(bad_rendering.md)
First line
```
Code
fence
```
Last line

Here's the link to the commonMark spec about this: https://spec.commonmark.org/0.31.2/#fenced-code-block

**Comment by Orc** [comment]
Both of those examples ended up being rendered by whatever markdown github uses (and, other than the text, are identical) — can you put them into a gist so I can see an unrendered version?

-jessica parsons

**Comment by Sebultura** [comment]
Oops sorry!
I have created "Good.md" and "Bad.md" gists, do you know how I can share those to you (they're public)?

**Comment by Orc** [comment]
Just send me links to the offending gists; that SHOULD work!

-Jessica Parsons

**Comment by Sebultura** [comment]
Take the Bad.md sample I provided you, it should give you the same result as Good.md (which isn't the case in Okular)

**Comment by Orc** [comment]
Good.md has a bunch of document.write()s in it;  are you sure that's what you were trying to render?

**Comment by Sebultura** [comment]
Sorry, it's a pain to manipulate links & edit with a smartphone 😁. The link to Good.md is fixed on my previous comment.

**Comment by Sebultura** [comment]
Thanks. So when we put a code block in the next line after a text, the standard result is to render it on the right of the text then if understand well?

**Comment by Sebultura** [comment]
Then let all markdown APIs handle this differently. Closing.

**Comment by Orc** [comment]
sorry I didn't reply to your message a month ago -- the mail appears to have vanished here -- but both github flavoured markdown and c\*mm\*nm\*rk are missing just what markdown is in this case.

It's not nearly as annoying as the GFM behavior of treating newlines in paragraphs as `<br/>`, but yeah it's gonna be one of those cases where parsers that adhere to the gruber/swartz standard are going to behave differently than c\*mm\*nm\*rk's reinvention of the language.

Sorry about that :-(
