### ISSUE TITLE
Intentional fallthroughs?

### ISSUE THREAD

**Issue by r-barnes** [Orc/discount#287]
Is the fallthrough on [this line](https://github.com/Orc/discount/blob/5e2f73aec4025b23a6d1c85b6c62f9653cccd9b9/generate.c#L1440) from the underscore case to the asterisk case intentional?

If not, can we use a `break;` to fix the bug? If so, can we use `__attribute__((fallthrough));` to mark it as explicit?

**Comment by Orc** [comment]
Yes, that is intentional;   if a leading emphasis looks like two characters, I first look for a two character match and if that fails I fall back to a one character match.


-jessica l. parsons

**Comment by Orc** [comment]
I'm going to close this issue because switch fallthrough is part of the language  (c.f. [Duff's Device](https://en.wikipedia.org/wiki/Duff%27s_device))
