### ISSUE TITLE
MKD_NOSTYLE flag is not documented

### ISSUE THREAD

**Issue by davidfstr** [Orc/discount#74]
The `MKD_NOSTYLE` flag is not documented on the table on this page:
http://www.pell.portland.or.us/~orc/Code/discount/

![screen shot 2013-05-27 at 5 41 43 pm](https://f.cloud.github.com/assets/764688/570141/753f1b6e-c72f-11e2-8184-e8feab91bef2.png)

**Comment by Orc** [comment]
Whoops! \*blush\* I never fixed this until now.   **NOW** it's documented.
