### ISSUE TITLE
MKD_TAGTEXT documentation is unclear

### ISSUE THREAD

**Issue by davidfstr** [Orc/discount#75]
In both `mkdio.h` and in the flags table on this page:
http://www.pell.portland.or.us/~orc/Code/discount/

The description for `MKD_TAGTEXT` is:
`process text inside an html tag; no <em>, no <bold>, no html or [] expansion`

It is not clear to me what this means. My best guess is that anything within `<html>` and `</html>` tags is output literally, without interpretation by Discount.

**Comment by Orc** [comment]
Also whoops;  you're right in that it's not particularly descriptive.  I've modified the description on the discount page, and will go back and update the manpages as well.

**Comment by Orc** [comment]
... and now the markdown(3) page is updated, only, um, 4 years late.
