### ISSUE TITLE
Footnote numbering within tables is incorrect

### ISSUE THREAD

**Issue by davidfstr** [Orc/discount#76]
**Affects:** Discount 2.1.6

**Input:**
```
Alpha[^AlphaF].

Column 1                         | Column 2
---------------------------------|--------------------------
Beta[^BetaF]                     | cell

[^AlphaF]: Alpha Footnote

[^BetaF]: Beta Footnote
```

**Output (Visual):**
![screen shot 2013-06-01 at 9 52 32 pm](https://f.cloud.github.com/assets/764688/595921/49081a54-cb40-11e2-932c-40a789547845.png)

Notice that both superscripted footnote references are incorrectly `1`. The backlinks for both footnotes (↩) also incorrectly both reference the `1` superscript. Finally the footnotes appear out of order at the bottom - that is the Alpha footnote is expected to occur before Beta since it was declared first.

**Output (HTML):**
```
<p>Alpha<sup id="fnref:1"><a href="#fn:1" rel="footnote">1</a></sup>.</p>

<table>
<thead>
<tr>
<th>Column 1                         </th>
<th> Column 2</th>
</tr>
</thead>
<tbody>
<tr>
<td>Beta<sup id="fnref:1"><a href="#fn:1" rel="footnote">1</a></sup>                     </td>
<td> cell</td>
</tr>
</tbody>
</table>

<div class="footnotes">
<hr/>
<ol>
<li id="fn:1">
<p>Beta Footnote<a href="#fnref:1" rev="footnote">&#8617;</a></p></li>
<li id="fn:1">
<p>Alpha Footnote<a href="#fnref:1" rev="footnote">&#8617;</a></p></li>
</ol>
</div>
```

**Note:**
It seems this problem only happens when a footnote reference is made inside a table.

**Comment by Orc** [comment]
Not this week (what **is** it about december and deadlines) but I've just pushed a version with the corrected data structures.   Sheeesh;  2 hours of work + testing, and it still took me a year and a half to get around to fixing it.

**Comment by SamWhited** [comment]
Hah, no worries; thanks @Orc.

**Comment by cloose** [comment]
Great @Orc. Will you also do a new official release, so that this is picked up by distros?

**Comment by Orc** [comment]
Yes, as soon as I've given it a couple of days in service (to make sure I didn't introduce any surprises)

**Comment by Orc** [comment]
And a new official release is out, so I'm gonna close this defect and wait for it to rematerialize
