### ISSUE TITLE
International characters disable neighboring emphasis markers

### ISSUE THREAD

**Issue by davidfstr** [Orc/discount#85]
**Affects:** Discount 2.1.6
**Environment:** Mac OS X 10.7.5 (probably not important)

```
$ discount/markdown
*foo ä bar*
^D
<p><em>foo ä bar</em></p>
```

This is correct.

```
$ discount/markdown
*ä foobar*
^D
<p>*ä foobar*</p>
```

Expected: `<p><em>ä foobar</em></p>`

```
$ discount/markdown
*foobar ä*
^D
<p>*foobar ä*</p>
```

Expected: `<p><em>foobar ä</em></p>`

**Comment by Orc** [comment]
The idea of redoing the inner workings seemed a bit daunting, so I didn't redo the guts of the code and now that I've got a new release I'm going to close this defect and move it to my LOOK AT ME! directory
