### ISSUE TITLE
Callback for code blocks

### ISSUE THREAD

**Issue by craigbarnes** [Orc/discount#96]
Would it be reasonable to add an API for setting a user callback for code blocks? The motivating use case is for compile-time (as opposed to JavaScript) syntax highlighting.

**Comment by Orc** [comment]
Okay, so this is now officially an ancient feature request and I've only just now gotten around to looking at it.   Still any interest in it, and are you talking just code blocks or blocks + inline chunks?

**Comment by mloskot** [comment]
@Orc Closed as in implemented?

**Comment by Orc** [comment]
Closed as in it's really old and the requester hasn't gotten back to me when I asked if he was interested and what scope he was looking at.

**Comment by mloskot** [comment]
Gotcha, thank you for confirmation.
